(()=> {
const C=window.KAREN_SUPABASE,L=window.SOLIDARITY_LOCALES,$=id=>document.getElementById(id),RTL=new Set(L.rtl||[]);
let lang=localStorage.getItem("solidarity_lang")||"en",state=null;
const t=k=>L.ui?.[lang]?.[k]||L.ui?.en?.[k]||k;
function euro(v){try{return new Intl.NumberFormat(lang,{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(Number(v||0))}catch{return "€"+Math.round(Number(v||0))}}
function dateFmt(v){if(!v)return"—";try{return new Intl.DateTimeFormat(lang,{day:"numeric",month:"short",year:"numeric"}).format(new Date(String(v).slice(0,10)+"T12:00:00"))}catch{return String(v)}}
async function rpc(name,body={}){const r=await fetch(C.url+"/rest/v1/rpc/"+name,{method:"POST",headers:{"Content-Type":"application/json",apikey:C.key},body:JSON.stringify(body)}),x=await r.text();if(!r.ok)throw Error(x||"request_failed");return x?JSON.parse(x):null}
function lc(c){const all=c?.localeContent||{};return all[lang]||all.en||{}}
function compute(d){const rows=(d.contributions||[]).filter(x=>["confirmed","received","refunded"].includes(x.status)),gross=rows.filter(x=>x.status!=="refunded").reduce((s,x)=>s+Number(x.amountCents||0),0),refunds=rows.filter(x=>x.status==="refunded").reduce((s,x)=>s+Number(x.amountCents||0),0),net=Math.max(0,gross-refunds),spent=(d.expenses||[]).filter(x=>x.status==="recorded").reduce((s,x)=>s+Number(x.amountCents||0),0),available=Math.max(0,net-spent),target=Number(d.campaign?.targetCents||0);return{rows,gross,refunds,net,spent,available,target,pct:target?Math.min(100,net/target*100):0}}
function drawCurve(d,m){const canvas=$("curve"),rect=canvas.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1),w=Math.max(700,Math.round(rect.width)),h=Math.max(320,Math.round(rect.height));canvas.width=w*dpr;canvas.height=h*dpr;const ctx=canvas.getContext("2d");ctx.scale(dpr,dpr);let sum=0;const s=m.rows.slice().sort((a,b)=>String(a.date||"").localeCompare(String(b.date||""))).map((x,i)=>{sum=Math.max(0,sum+(x.status==="refunded"?-1:1)*Number(x.amountCents||0));return{i,value:sum,date:x.date}});const p={l:58,r:24,t:28,b:45},iw=w-p.l-p.r,ih=h-p.t-p.b,max=Math.max(m.target,...s.map(x=>x.value),1),sx=i=>s.length<2?p.l+iw/2:p.l+i/(s.length-1)*iw,sy=v=>p.t+ih-v/max*ih;ctx.clearRect(0,0,w,h);ctx.font="10px Inter,system-ui";for(let i=0;i<=4;i++){const v=max*i/4,y=sy(v);ctx.strokeStyle="rgba(117,109,101,.18)";ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(w-p.r,y);ctx.stroke();ctx.fillStyle="#756d65";ctx.textAlign="right";ctx.fillText(euro(v/100),p.l-7,y+3)}if(m.target){const y=sy(m.target);ctx.strokeStyle="#d5a447";ctx.lineWidth=2;ctx.setLineDash([8,7]);ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(w-p.r,y);ctx.stroke();ctx.setLineDash([])}if(!s.length)return;const pts=s.map((x,i)=>[sx(i),sy(x.value)]);ctx.beginPath();ctx.moveTo(pts[0][0],pts[0][1]);for(let i=1;i<pts.length;i++){const[a,b]=pts[i-1],[c,d1]=pts[i],mx=(a+c)/2;ctx.bezierCurveTo(mx,b,mx,d1,c,d1)}ctx.strokeStyle="#c12f45";ctx.lineWidth=5;ctx.lineCap="round";ctx.stroke();pts.forEach(([x,y],i)=>{ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.fillStyle="#fffaf2";ctx.fill();ctx.strokeStyle="#c12f45";ctx.lineWidth=3;ctx.stroke();ctx.fillStyle="#756d65";ctx.textAlign=i===0?"left":i===pts.length-1?"right":"center";ctx.fillText(dateFmt(s[i].date),x,h-16)})}
function render(d,supporters){state=d;const c=d.campaign||{},m=compute(d),content=lc(c),enabled=c.enabledLocales?.length?c.enabledLocales:["en","fr"];if(!enabled.includes(lang))lang=enabled.includes("en")?"en":enabled[0];document.documentElement.lang=lang;document.documentElement.dir=RTL.has(lang)?"rtl":"ltr";const sel=$("languageSelect");sel.replaceChildren();enabled.forEach(code=>{const o=document.createElement("option");o.value=code;o.textContent=L.names[code]||code;o.selected=code===lang;sel.append(o)});$("title").textContent=content.title||c.title||"Campaign report";$("story").textContent=content.story||c.story_en||"";$("net").textContent=euro(m.net/100);$("goal").textContent="of "+euro(m.target/100);$("supporters").textContent=supporters.length;$("events").textContent=m.rows.length;$("refunds").textContent=euro(m.refunds/100);$("spent").textContent=euro(m.spent/100);$("available").textContent=euro(m.available/100);$("progress").textContent=Math.round(m.pct)+"%";const ms=$("milestones");ms.replaceChildren();(d.milestones||[]).forEach(x=>{const v=Number(x.thresholdCents||0),pct=v?Math.min(100,m.net/v*100):0,item=document.createElement("article");item.className="item";item.innerHTML="<strong>"+((lang==="fr"&&x.label_fr)||x.label_en||"Milestone")+"</strong><span>"+euro(v/100)+" · "+Math.round(pct)+"%</span><div class='bar'><i style='width:"+pct+"%'></i></div>";ms.append(item)});$("milestoneSection").style.display=(d.milestones||[]).length?"":"none";const reg=$("registry");reg.replaceChildren();supporters.forEach(x=>{const r=document.createElement("div");r.className="row";const b=document.createElement("b"),s=document.createElement("span");b.textContent=x.supporterId||"S-????????";s.textContent=(x.publicNameConsent&&x.name?x.name:t("anonymous"))+" · "+x.eventCount+" "+(L.ui?.[lang]?.events||"events")+" · "+euro(Number(x.netCents||0)/100);r.append(b,s);reg.append(r)});const ex=$("expenses");ex.replaceChildren();(d.expenses||[]).forEach(x=>{const r=document.createElement("div");r.className="row";const b=document.createElement("b"),s=document.createElement("span");b.textContent=(lang==="fr"&&x.label_fr)||x.label_en||"Expense";s.textContent=euro(Number(x.amountCents||0)/100)+" · "+dateFmt(x.spentOn);r.append(b,s);ex.append(r)});if(!(d.expenses||[]).length)ex.textContent="No public disbursements recorded.";const up=$("updates");up.replaceChildren();(d.updates||[]).forEach(x=>{const a=document.createElement("article");a.className="item";const h=document.createElement("strong"),p=document.createElement("p");h.textContent=(lang==="fr"&&x.title_fr)||x.title_en||"Update";p.textContent=(lang==="fr"&&x.body_fr)||x.body_en||"";a.append(h,p);up.append(a)});$("updatesSection").style.display=(d.updates||[]).length?"":"none";$("thanks").textContent=content.thankYou||c.thankYou_en||L.ui?.[lang]?.quote||L.ui.en.quote;$("timestamp").textContent="Generated "+new Date().toLocaleString(lang);requestAnimationFrame(()=>drawCurve(d,m))}
async function refresh(){const [d,s]=await Promise.all([rpc("karen_public_state"),rpc("solidarity_public_supporters")]);render(d,Array.isArray(s)?s:[])}
$("languageSelect").onchange=e=>{lang=e.target.value;localStorage.setItem("solidarity_lang",lang);refresh()};$("printBtn").onclick=()=>window.print();window.addEventListener("resize",()=>{if(state)requestAnimationFrame(()=>drawCurve(state,compute(state)))});refresh();setInterval(refresh,30000);
})();