(()=>{const C=window.KAREN_SUPABASE;const $=id=>document.getElementById(id);let secret=null,admin=null;
async function rpc(name,body={}){const r=await fetch(C.url+"/rest/v1/rpc/"+name,{method:"POST",headers:{"Content-Type":"application/json",apikey:C.key},body:JSON.stringify(body)});const t=await r.text();if(!r.ok)throw Error(t);return t?JSON.parse(t):null}
async function digest(v){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function publicRefresh(){try{const d=await rpc("karen_public_state");if(typeof window.render==="function")window.render(d)}catch{}}
window.refreshKarenFund=publicRefresh;publicRefresh();setInterval(publicRefresh,30000);
const dialog=$("adminDialog"),mount=$("adminMount");$("adminBtn").onclick=()=>{dialog.showModal();login()};$("adminClose").onclick=()=>dialog.close();
function clear(){mount.replaceChildren()}function make(tag,text){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e}
function login(){clear();const p=make("p","Enter organizer key");const i=make("input");i.type="password";i.autocomplete="current-password";i.style.cssText="width:100%;padding:10px;border:1px solid #d9d5ce;border-radius:9px";const b=make("button","Unlock");b.type="button";b.style.cssText="margin-top:10px;padding:10px 12px;border:0;border-radius:9px;background:#141618;color:white;font-weight:800";const m=make("div","");m.style.cssText="margin-top:8px;color:#8d1c2c;font-size:.8rem";b.onclick=async()=>{m.textContent="Checking…";try{secret=await digest(i.value);admin=await rpc("karen_admin_action",{p_secret_digest:secret,p_action:{action:"list"}});panel()}catch{m.textContent="Wrong key."}};mount.append(p,i,b,m);setTimeout(()=>i.focus(),50)}
function panel(){clear();const top=make("div");top.style.cssText="display:flex;justify-content:space-between;align-items:center;gap:10px";top.append(make("strong","Fund administration"));const lock=make("button","Lock");lock.type="button";lock.onclick=()=>{secret=null;admin=null;login()};top.append(lock);mount.append(top);const rows=make("div");rows.style.marginTop="14px";(admin.contributions||[]).forEach(x=>{const r=make("div");r.style.cssText="padding:12px 0;border-bottom:1px solid #d9d5ce";const h=make("div");h.style.cssText="display:flex;justify-content:space-between;gap:10px";h.append(make("strong",x.real_name),make("span",(x.amount_cents/100).toLocaleString(undefined,{style:"currency",currency:"EUR"})));const lab=make("label");lab.style.cssText="display:flex;align-items:center;gap:7px;margin-top:8px;font-size:.78rem";const cb=make("input");cb.type="checkbox";cb.checked=x.public_name===true;lab.append(cb,document.createTextNode("Show name publicly"));cb.onchange=()=>save({action:"update",id:x.id,public_name:cb.checked,public_alias:cb.checked?x.real_name:null});r.append(h,make("div",x.contributed_on),lab);rows.append(r)});mount.append(rows);const add=make("button","Add contribution");add.type="button";add.style.marginTop="14px";add.onclick=addPrompt;mount.append(add)}
async function save(a){await rpc("karen_admin_action",{p_secret_digest:secret,p_action:a});admin=await rpc("karen_admin_action",{p_secret_digest:secret,p_action:{action:"list"}});panel();await publicRefresh()}
async function addPrompt(){const name=prompt("Contributor name");if(!name)return;const amount=Number(prompt("Amount in EUR"));if(!(amount>0))return;const date=prompt("Date YYYY-MM-DD",new Date().toISOString().slice(0,10));if(!date)return;const pub=confirm("Show name publicly?");await save({action:"add",real_name:name.trim(),amount_cents:Math.round(amount*100),contributed_on:date,public_name:pub,public_alias:pub?name.trim():null})}
})();