(()=> {
const C=window.KAREN_SUPABASE;
const $=id=>document.getElementById(id);
const I=window.SolidarityI18N;
const Charts=window.SolidarityCharts;
const Registry=window.SolidarityRegistry;
let current=null;
let lang=localStorage.getItem("solidarity_lang")||((navigator.language||"en").split("-")[0]);
let nonce=Number(sessionStorage.getItem("supporter_shuffle")||Date.now());

function t(k){return I.get(lang,k)}
function localeCode(){return {en:"en-GB",fr:"fr-FR",de:"de-DE",es:"es-ES",it:"it-IT",pt:"pt-PT",nl:"nl-NL",ar:"ar-EG"}[lang]||"en-GB"}
function euro(v){return new Intl.NumberFormat(localeCode(),{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(Number(v||0))}
function dateFmt(v,short=false){if(!v)return"—";const d=new Date(String(v).slice(0,10)+"T12:00:00");try{return new Intl.DateTimeFormat(localeCode(),short?{day:"numeric",month:"short"}:{day:"numeric",month:"short",year:"numeric"}).format(d)}catch{return String(v).slice(0,10)}}
async function rpc(name,body={}){const r=await fetch(C.url+"/rest/v1/rpc/"+name,{method:"POST",headers:{"Content-Type":"application/json",apikey:C.key},body:JSON.stringify(body)});const tx=await r.text();if(!r.ok)throw Error(tx||"request_failed");return tx?JSON.parse(tx):null}
function compute(d){const rows=(d.contributions||[]).filter(x=>["confirmed","received","refunded"].includes(x.status)),pos=rows.filter(x=>x.status!=="refunded"),gross=pos.reduce((s,x)=>s+Number(x.amountCents||0),0),refunds=rows.filter(x=>x.status==="refunded").reduce((s,x)=>s+Number(x.amountCents||0),0),net=Math.max(0,gross-refunds),spent=(d.expenses||[]).filter(x=>x.status==="recorded").reduce((s,x)=>s+Number(x.amountCents||0),0),available=Math.max(0,net-spent),target=Number(d.campaign?.targetCents||0);return{rows,pos,gross,refunds,net,spent,available,target,pct:target?Math.min(100,net/target*100):0}}
function localeContent(c){const all=c?.localeContent||{};return all[lang]||all.en||{}}
function toast(msg){const e=$("toast");if(!e)return;e.textContent=msg;e.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.remove("show"),2200)}
function statusLabel(s){const maps={fr:{active:"EN DIRECT",goal_reached:"OBJECTIF ATTEINT",closed:"CLÔTURÉE",archived:"ARCHIVÉE",draft:"BROUILLON"},de:{active:"LIVE",goal_reached:"ZIEL ERREICHT",closed:"BEENDET",archived:"ARCHIVIERT",draft:"ENTWURF"},ar:{active:"مباشر",goal_reached:"تم بلوغ الهدف",closed:"مغلق",archived:"مؤرشف",draft:"مسودة"}};return maps[lang]?.[s]||{active:"LIVE",goal_reached:"GOAL REACHED",closed:"CLOSED",archived:"ARCHIVED",draft:"DRAFT"}[s]||"LIVE"}
function renderLanguages(c){const sel=$("languageSelect"),enabled=c?.enabledLocales?.length?c.enabledLocales:["en","fr"];if(!enabled.includes(lang))lang=enabled.includes("en")?"en":enabled[0];sel.replaceChildren();enabled.forEach(code=>{const o=document.createElement("option");o.value=code;o.textContent=I.languages[code]||code.toUpperCase();o.selected=code===lang;sel.append(o)});document.documentElement.lang=lang;document.documentElement.dir=I.rtl.has(lang)?"rtl":"ltr";document.querySelectorAll("[data-i18n]").forEach(el=>{const v=t(el.dataset.i18n);if(v)el.textContent=v})}
function renderStats(m){const vals=m.pos.map(x=>Number(x.amountCents||0)).sort((a,b)=>a-b),mean=vals.length?m.gross/vals.length:0,median=vals.length?(vals.length%2?vals[Math.floor(vals.length/2)]:(vals[vals.length/2-1]+vals[vals.length/2])/2):0,min=vals[0]||0,max=vals.at(-1)||0,gap=Math.max(0,m.target-m.net);$("statNet").textContent=euro(m.net/100);$("statMean").textContent=euro(mean/100);$("statMedian").textContent=euro(median/100);$("statRange").textContent=euro(min/100)+"–"+euro(max/100);$("statGap").textContent=euro(gap/100);$("statNeeded").textContent=median?Math.ceil(gap/median):"—"}
function renderMilestones(d,m){const sec=$("milestonesSection"),wrap=$("milestones"),show=d.campaign?.showMilestones!==false&&(d.milestones||[]).length;sec.classList.toggle("hidden",!show);wrap.replaceChildren();if(!show)return;(d.milestones||[]).forEach(x=>{const v=Number(x.thresholdCents||0),p=v?Math.min(100,m.net/v*100):0,c=document.createElement("article");c.className="milestone"+(m.net>=v?" done":"");const a=document.createElement("strong");a.textContent=(lang==="fr"&&x.label_fr)||x.label_en||t("milestones");const b=document.createElement("span");b.textContent=euro(v/100)+" · "+(m.net>=v?t("goalReached"):Math.round(p)+"%");const tr=document.createElement("div");tr.className="milestone-bar";const fill=document.createElement("div");fill.style.width=p+"%";tr.append(fill);c.append(a,b,tr);wrap.append(c)})}
function renderFinance(d,m){$("grossRaised").textContent=euro(m.gross/100);$("refundsTotal").textContent=euro(m.refunds/100);$("spentTotal").textContent=euro(m.spent/100);$("availableTotal").textContent=euro(m.available/100);$("refundStat").classList.toggle("hidden",!m.refunds);$("spentStat").classList.toggle("hidden",!m.spent);const lc=localeContent(d.campaign),note=lc.overfunding||((lang==="fr"&&d.campaign?.overfunding_fr)||d.campaign?.overfunding_en||"");$("overfundingNote").textContent=note;$("overfundingNote").classList.toggle("hidden",!note)}
function renderUpdates(d){const sec=$("updatesSection"),wrap=$("updatesList"),rows=d.updates||[],show=d.campaign?.showUpdates!==false&&rows.length;sec.classList.toggle("hidden",!show);wrap.replaceChildren();if(!show)return;rows.forEach(x=>{const c=document.createElement("article");c.className="update-card";const tm=document.createElement("time"),h=document.createElement("h3"),p=document.createElement("p");tm.textContent=dateFmt(x.publishedAt);h.textContent=(lang==="fr"&&x.title_fr)||x.title_en||t("updates");p.textContent=(lang==="fr"&&x.body_fr)||x.body_en||"";c.append(tm,h,p);wrap.append(c)})}
function renderLedger(d,m){const det=$("ledgerDetails"),wrap=$("ledger"),show=d.campaign?.showLedger!==false;det.classList.toggle("hidden",!show);wrap.replaceChildren();if(!show)return;m.rows.slice().sort((a,b)=>String(b.date||"").localeCompare(String(a.date||""))).forEach((x,i)=>{const r=document.createElement("div");r.className="ledger-row";const n=document.createElement("span");n.textContent=String(m.rows.length-i).padStart(2,"0");const main=document.createElement("div"),st=document.createElement("strong"),meta=document.createElement("div");meta.className="ledger-meta";st.textContent=x.publicNameConsent&&x.name?x.name:t("anonymous");meta.textContent=dateFmt(x.date);const tag=document.createElement("span");tag.className="tag "+(x.status==="refunded"?"refund":"ok");tag.textContent=x.status==="refunded"?t("refunded"):t("confirmed");meta.append(tag);main.append(st,meta);const a=document.createElement("span");a.className="ledger-amount"+(x.status==="refunded"?" refund":"");a.textContent=(x.status==="refunded"?"−":"")+euro(Number(x.amountCents||0)/100);r.append(n,main,a);wrap.append(r)})}
function renderExpenses(d){const det=$("expensesDetails"),wrap=$("expensesList"),rows=(d.expenses||[]).filter(x=>x.status==="recorded"),show=d.campaign?.showExpenses!==false&&rows.length;det.classList.toggle("hidden",!show);wrap.replaceChildren();if(!show)return;rows.forEach((x,i)=>{const r=document.createElement("div");r.className="expense-row";const n=document.createElement("span");n.textContent=String(i+1).padStart(2,"0");const main=document.createElement("div"),st=document.createElement("strong"),meta=document.createElement("div");meta.className="expense-meta";st.textContent=(lang==="fr"&&x.label_fr)||x.label_en||t("expenses");const note=(lang==="fr"&&x.note_fr)||x.note_en||"";meta.textContent=dateFmt(x.spentOn)+(note?" · "+note:"");main.append(st,meta);const a=document.createElement("span");a.className="expense-amount";a.textContent=euro(Number(x.amountCents||0)/100);r.append(n,main,a);wrap.append(r)})}

function render(d){current=d;window.__fund=d;const c=d.campaign||{},m=compute(d),lc=localeContent(c);renderLanguages(c);document.title=(lc.title||c.title||"Solidarity Fund")+" · Live";$("brandCampaign").textContent=lc.title||c.title||"Solidarity Fund";$("campaignKicker").textContent=(c.beneficiary||"SOLIDARITY").toUpperCase();$("campaignTitle").textContent=lc.subtitle||c.subtitle||lc.title||c.title||"";$("campaignStory").textContent=lc.story||c.story_en||"";$("campaignStatus").textContent=statusLabel(c.status);$("lastUpdated").textContent=dateFmt(d.updated);$("raisedTotal").textContent=euro(m.net/100);$("goalText").textContent=euro(m.target/100);$("progressPct").textContent=Math.round(m.pct)+"%";$("supporterCount").textContent=(d.supporters||[]).length||m.pos.length;$("remainingAmount").textContent=euro(Math.max(0,m.target-m.net)/100);$("progressLine").style.width=m.pct+"%";
 const payUrl=c.paymentUrl||C.paypalPoolUrl||"https://www.paypal.com/pool/9tfV5v7iJ3",label=lc.paymentLabel||c.paymentLabel_en||t("payWithPayPal"),closed=["draft","closed","archived"].includes(c.status);["topPayBtn","heroPayBtn","mobilePayBtn"].forEach(id=>{const a=$(id);a.href=payUrl;a.classList.toggle("hidden",closed)});$("paymentLabel").textContent=label;document.querySelectorAll('[data-i18n="payWithPayPal"]').forEach(e=>e.textContent=label);
 renderStats(m);const showAnalytics=c.showAnalytics!==false;$("observatory").classList.toggle("hidden",!showAnalytics);if(showAnalytics)Charts.renderAll({state:d,m,euro,dateFmt,t});renderMilestones(d,m);$("supportersSection").classList.toggle("hidden",c.showSupporters===false);if(c.showSupporters!==false)Registry.render({container:$("supporterWall"),supporters:d.supporters||[],locale:localeCode(),t,euro,nonce});renderFinance(d,m);renderUpdates(d);renderLedger(d,m);renderExpenses(d);$("footerCampaign").textContent=(lc.title||c.title||"Solidarity Fund")+" · "+statusLabel(c.status)}
window.render=render;
async function refresh(){try{const [d,s]=await Promise.all([rpc("karen_public_state"),rpc("solidarity_public_supporters")]);d.supporters=Array.isArray(s)?s:[];render(d)}catch{$("campaignStory").textContent=t("noData")}}
window.refreshKarenFund=refresh;

$("languageSelect").onchange=e=>{lang=e.target.value;localStorage.setItem("solidarity_lang",lang);setLanguage(lang)};
$("reshuffleBtn").onclick=()=>{nonce=Date.now()+Math.floor(Math.random()*1e6);sessionStorage.setItem("supporter_shuffle",String(nonce));if(current)Registry.render({container:$("supporterWall"),supporters:current.supporters||[],locale:localeCode(),t,euro,nonce})};
$("shareBtn").onclick=async()=>{const c=current?.campaign||{},lc=localeContent(c),m=current?compute(current):null,data={title:lc.title||c.title||"Solidarity Fund",text:(lc.subtitle||c.subtitle||"")+" "+(m?euro(m.net/100):""),url:location.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);toast("Link copied")}}catch{}};

async function consentFlow(){const token=new URLSearchParams(location.search).get("consent");if(!token)return;const d=$("consentDialog"),m=$("consentMount");$("consentClose").onclick=()=>d.close();try{const s=await rpc("solidarity_consent_state",{p_token:token});m.replaceChildren();const p=document.createElement("p");p.textContent=euro(Number(s.amountCents||0)/100)+" · "+dateFmt(s.date);const cb=document.createElement("input");cb.type="checkbox";cb.checked=!!s.publicName;const lab=document.createElement("label");lab.className="consent-option";lab.append(cb,document.createTextNode(" "+t("privacy")));const alias=document.createElement("input");alias.type="text";alias.value=s.publicAlias||"";alias.placeholder=t("anonymous");const save=document.createElement("button");save.className="save-consent";save.textContent="Save";save.onclick=async()=>{await rpc("solidarity_consent_set",{p_token:token,p_public_name:cb.checked,p_alias:cb.checked?alias.value.trim():null});await refresh();toast(t("confirmed"))};m.append(p,lab,alias,save);d.showModal()}catch{}}

refresh().then(consentFlow);setInterval(refresh,30000);
})();