/* Calendar formats are independent of the viewer's local timezone. */
(function(root){'use strict';
const zone='Europe/Berlin',compact=d=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,''),dayAfter=s=>new Date(Date.parse(s+'T12:00:00Z')+86400000).toISOString().slice(0,10);
function utc(date,time){const target=Date.parse(date+'T'+time+':00Z');let ms=target;for(let i=0;i<3;i++){const parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(ms)).map(p=>[p.type,p.value]));const wall=Date.parse(`${parts.year}-${parts.month}-${parts.day}T${parts.hour}:${parts.minute}:${parts.second}Z`);ms+=target-wall}return new Date(ms)}
function details(e){if(!/^\d{4}-\d{2}-\d{2}$/.test(e.date||'')||['cancelled','postponed'].includes(e.status))throw Error('Wait for a confirmed date before adding this event.');const timed=/^\d{2}:\d{2}$/.test(e.time||''),start=timed?utc(e.date,e.time):e.date,end=timed?(e.endTime?utc(e.endTime<=e.time?dayAfter(e.date):e.date,e.endTime):new Date(start.getTime()+3600000)):dayAfter(e.date);const url=new URL('https://karen-solidarity.vercel.app/');url.searchParams.set('event',e.id);url.hash='events';const notes=[e.description,e.note,!timed?'Time to be confirmed. This is an all-day placeholder.':!e.endTime?'End time unconfirmed: this calendar copy reserves one hour.':'','Check the hub for changes. This calendar copy does not update automatically.',url.href].filter(Boolean).join('\n\n');return {timed,start,end,title:e.title+(!timed?' (time TBD)':''),location:[e.place,e.address].filter(Boolean).join(', '),notes,url:url.href}}
function links(e){const d=details(e);const g=new URL('https://calendar.google.com/calendar/r/eventedit');g.search=new URLSearchParams({action:'TEMPLATE',text:d.title,dates:d.timed?compact(d.start)+'/'+compact(d.end):d.start.replaceAll('-','')+'/'+d.end.replaceAll('-',''),stz:zone,etz:zone,ctz:zone,details:d.notes,location:d.location});const outlook=host=>{const u=new URL('https://'+host+'/calendar/0/deeplink/compose');u.search=new URLSearchParams({path:'/calendar/action/compose',rru:'addevent',subject:d.title,body:d.notes,location:d.location,startdt:d.timed?d.start.toISOString():d.start,enddt:d.timed?d.end.toISOString():d.end,allday:String(!d.timed)});return u.href};return {google:g.href,outlook:outlook('outlook.live.com'),office:outlook('outlook.office.com')}}
const escape=s=>String(s||'').replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');
function fold(line){let result='',length=0;for(const c of line){const bytes=new TextEncoder().encode(c).length;if(length+bytes>75){result+='\r\n ';length=1}result+=c;length+=bytes}return result}
function ics(events,reminder=120){const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Red Banner//Collective Agenda//EN','CALSCALE:GREGORIAN','METHOD:PUBLISH'];for(const e of events){const d=details(e);lines.push('BEGIN:VEVENT','UID:'+escape(e.id)+'@red-banner','DTSTAMP:'+compact(new Date()),d.timed?'DTSTART:'+compact(d.start):'DTSTART;VALUE=DATE:'+d.start.replaceAll('-',''),d.timed?'DTEND:'+compact(d.end):'DTEND;VALUE=DATE:'+d.end.replaceAll('-',''),'SUMMARY:'+escape(d.title),'LOCATION:'+escape(d.location),'DESCRIPTION:'+escape(d.notes),'URL:'+d.url);if(d.timed&&Number(reminder)>0)lines.push('BEGIN:VALARM','TRIGGER:-PT'+Number(reminder)+'M','ACTION:DISPLAY','DESCRIPTION:'+escape(e.title),'END:VALARM');lines.push('END:VEVENT')}lines.push('END:VCALENDAR');return lines.map(fold).join('\r\n')+'\r\n'}
const api={details,links,ics,utc};if(typeof module!=='undefined')module.exports=api;else root.RBCalendarTools=api;
})(typeof window!=='undefined'?window:globalThis);
