(()=> {
const C=window.KAREN_SUPABASE,L=window.SOLIDARITY_LOCALES,$=id=>document.getElementById(id);
const RTL=new Set(L.rtl||[]);
let lang=localStorage.getItem("solidarity_lang")||((navigator.language||"en").split("-")[0]),state=null;
const EXTRA={
en:{campaignCurveText:"Each rise is a collective act. The gold horizon is the goal.",now:"Now",qr:"Show QR",exploreData:"Explore the data →",scanToContribute:"Scan to contribute"},
fr:{campaignCurveText:"Chaque hausse est un acte collectif. L’horizon doré est l’objectif.",now:"Maintenant",qr:"Afficher le QR",exploreData:"Explorer les données →",scanToContribute:"Scanner pour contribuer"},
de:{campaignCurveText:"Jeder Anstieg ist ein kollektiver Akt. Der goldene Horizont ist das Ziel.",now:"Jetzt",qr:"QR anzeigen",exploreData:"Daten erkunden →",scanToContribute:"Scannen zum Beitragen"},
es:{campaignCurveText:"Cada subida es un acto colectivo. El horizonte dorado es la meta.",now:"Ahora",qr:"Mostrar QR",exploreData:"Explorar los datos →",scanToContribute:"Escanear para contribuir"},
it:{campaignCurveText:"Ogni salita è un atto collettivo. L’orizzonte dorato è l’obiettivo.",now:"Ora",qr:"Mostra QR",exploreData:"Esplora i dati →",scanToContribute:"Scansiona per contribuire"},
pt:{campaignCurveText:"Cada subida é um ato coletivo. O horizonte dourado é a meta.",now:"Agora",qr:"Mostrar QR",exploreData:"Explorar os dados →",scanToContribute:"Digitalize para contribuir"},
nl:{campaignCurveText:"Elke stijging is een collectieve daad. De gouden horizon is het doel.",now:"Nu",qr:"QR tonen",exploreData:"Bekijk de data →",scanToContribute:"Scan om bij te dragen"},
ar:{campaignCurveText:"كل ارتفاع هو فعل جماعي. الأفق الذهبي هو الهدف.",now:"الآن",qr:"عرض رمز QR",exploreData:"استكشاف البيانات ←",scanToContribute:"امسح للمساهمة"}
};
const t=k=>EXTRA[lang]?.[k]||L.ui?.[lang]?.[k]||EXTRA.en[k]||L.ui?.en?.[k]||k;
function euro(n){try{return new Intl.NumberFormat(lang,{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(Number(n||0))}catch{return "€"+Math.round(Number(n||0))}}
function dateFmt(v){if(!v)return"—";const d=new Date(String(v).slice(0,10)+"T12:00:00");try{return new Intl.DateTimeFormat(lang,{day:"numeric",month:"short",year:"numeric"}).format(d)}catch{return String(v)}}
async function rpc(name,body={}){const r=await fetch(C.url+"/rest/v1/rpc/"+name,{method:"POST",headers:{"Content-Type":"application/json",apikey:C.key},body:JSON.stringify(body)}),x=await r.text();if(!r.ok)throw Error(x||"request_failed");return x?JSON.parse(x):null}
function localeContent(c){const all=c?.localeContent||{};return all[lang]||all.en||{}}
function compute(d){const rows=(d.contributions||[]).filter(x=>["confirmed","received","refunded"].includes(x.status)),gross=rows.filter(x=>x.status!=="refunded").reduce((s,x)=>s+Number(x.amountCents||0),0),refunds=rows.filter(x=>x.status==="refunded").reduce((s,x)=>s+Number(x.amountCents||0),0),net=Math.max(0,gross-refunds),target=Number(d.campaign?.targetCents||0);return{rows,gross,refunds,net,target,pct:target?Math.min(100,net/target*100):0}}
function statusLabel(s){const M={fr:{active:"EN DIRECT",goal_reached:"OBJECTIF ATTEINT",closed:"CLÔTURÉE",archived:"ARCHIVÉE",draft:"BROUILLON"},de:{active:"LIVE",goal_reached:"ZIEL ERREICHT",closed:"BEENDET",archived:"ARCHIVIERT",draft:"ENTWURF"},es:{active:"EN VIVO",goal_reached:"OBJETIVO ALCANZADO",closed:"CERRADA",archived:"ARCHIVADA",draft:"BORRADOR"},it:{active:"LIVE",goal_reached:"OBIETTIVO RAGGIUNTO",closed:"CHIUSA",archived:"ARCHIVIATA",draft:"BOZZA"},pt:{active:"AO VIVO",goal_reached:"META ALCANÇADA",closed:"ENCERRADA",archived:"ARQUIVADA",draft:"RASCUNHO"},nl:{active:"LIVE",goal_reached:"DOEL BEREIKT",closed:"GESLOTEN",archived:"GEARCHIVEERD",draft:"CONCEPT"},ar:{active:"مباشر",goal_reached:"تم بلوغ الهدف",closed:"مغلق",archived:"مؤرشف",draft:"مسودة"}};return M[lang]?.[s]||({active:"LIVE",goal_reached:"GOAL REACHED",closed:"CLOSED",archived:"ARCHIVED",draft:"DRAFT"}[s]||"LIVE")}
function fillLanguages(c){const sel=$("languageSelect"),enabled=c?.enabledLocales?.length?c.enabledLocales:["en","fr"];if(!enabled.includes(lang))lang=enabled.includes("en")?"en":enabled[0];sel.replaceChildren();enabled.forEach(code=>{const o=document.createElement("option");o.value=code;o.textContent=L.names[code]||code.toUpperCase();o.selected=code===lang;sel.append(o)})}
function applyLanguage(){document.documentElement.lang=lang;document.documentElement.dir=RTL.has(lang)?"rtl":"ltr";document.querySelectorAll("[data-i18n]").forEach(el=>el.textContent=t(el.dataset.i18n))}
function series(rows){let sum=0;return rows.slice().sort((a,b)=>String(a.date||"").localeCompare(String(b.date||""))).map((x,i)=>{sum=Math.max(0,sum+(x.status==="refunded"?-1:1)*Number(x.amountCents||0));return{i,value:sum,date:x.date,status:x.status}})}
function drawCurve(){
 if(!state)return;
 const canvas=$("campaignCurve"),rect=canvas.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1),w=Math.max(600,Math.round(rect.width)),h=Math.max(300,Math.round(rect.height));
 canvas.width=w*dpr;canvas.height=h*dpr;const ctx=canvas.getContext("2d");ctx.scale(dpr,dpr);
 const m=compute(state),s=series(m.rows),pad={l:58,r:28,t:30,b:46},iw=w-pad.l-pad.r,ih=h-pad.t-pad.b,max=Math.max(m.target,...s.map(x=>x.value),1),sx=i=>s.length<2?pad.l+iw/2:pad.l+i/(s.length-1)*iw,sy=v=>pad.t+ih-(v/max)*ih;
 ctx.clearRect(0,0,w,h);ctx.font="11px Inter, system-ui";ctx.textBaseline="middle";
 for(let i=0;i<=4;i++){const v=max*i/4,y=sy(v);ctx.strokeStyle="rgba(117,109,101,.18)";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();ctx.fillStyle="#756d65";ctx.textAlign="right";ctx.fillText(euro(v/100),pad.l-8,y)}
 if(m.target){const y=sy(m.target);ctx.strokeStyle="#d7a64a";ctx.lineWidth=2;ctx.setLineDash([8,7]);ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle="#9a742c";ctx.textAlign="right";ctx.fillText((L.ui?.[lang]?.goal||"Goal")+" "+euro(m.target/100),w-pad.r,y-12)}
 if(!s.length)return;
 const pts=s.map((p,i)=>[sx(i),sy(p.value)]),grad=ctx.createLinearGradient(0,pad.t,0,pad.t+ih);grad.addColorStop(0,"rgba(195,47,70,.28)");grad.addColorStop(1,"rgba(195,47,70,0)");
 ctx.beginPath();ctx.moveTo(pts[0][0],pts[0][1]);for(let i=1;i<pts.length;i++){const [x0,y0]=pts[i-1],[x1,y1]=pts[i],mx=(x0+x1)/2;ctx.bezierCurveTo(mx,y0,mx,y1,x1,y1)}ctx.lineTo(pts.at(-1)[0],pad.t+ih);ctx.lineTo(pts[0][0],pad.t+ih);ctx.closePath();ctx.fillStyle=grad;ctx.fill();
 ctx.beginPath();ctx.moveTo(pts[0][0],pts[0][1]);for(let i=1;i<pts.length;i++){const [x0,y0]=pts[i-1],[x1,y1]=pts[i],mx=(x0+x1)/2;ctx.bezierCurveTo(mx,y0,mx,y1,x1,y1)}ctx.strokeStyle="#c32f46";ctx.lineWidth=5;ctx.lineCap="round";ctx.stroke();
 pts.forEach(([x,y],i)=>{ctx.beginPath();ctx.arc(x,y,s[i].status==="refunded"?7:5,0,Math.PI*2);ctx.fillStyle=s[i].status==="refunded"?"#862233":"#fffaf2";ctx.fill();ctx.strokeStyle="#c32f46";ctx.lineWidth=3;ctx.stroke();if(s.length<=8||i===0||i===s.length-1){ctx.fillStyle="#756d65";ctx.font="10px Inter, system-ui";ctx.textAlign=i===0?"left":i===s.length-1?"right":"center";ctx.fillText(dateFmt(s[i].date).replace(/\s\d{4}.*/,""),x,h-18)}});
 $("curveNow").textContent=euro(m.net/100)
}
function renderMilestones(d,m){const sec=$("campaignMilestones"),wrap=$("milestoneLine"),rows=d.milestones||[];sec.classList.toggle("hidden",!rows.length||d.campaign?.showMilestones===false);wrap.replaceChildren();rows.forEach(x=>{const v=Number(x.thresholdCents||0),p=v?Math.min(100,m.net/v*100):0,c=document.createElement("article");c.className="campaign-milestone"+(m.net>=v?" reached":"");const a=document.createElement("strong"),b=document.createElement("span"),bar=document.createElement("div"),fill=document.createElement("i");a.textContent=(lang==="fr"&&x.label_fr)||x.label_en||t("milestones");b.textContent=euro(v/100)+" · "+(m.net>=v?t("goalReached"):Math.round(p)+"%");bar.className="bar";fill.style.width=p+"%";bar.append(fill);c.append(a,b,bar);wrap.append(c)})}
function renderSupporters(list){const w=$("supporterSummary");w.replaceChildren();(list||[]).slice(0,12).forEach(x=>{const c=document.createElement("div");c.className="supporter-id";const id=document.createElement("b"),meta=document.createElement("span");id.textContent=x.supporterId||"S-????????";meta.textContent=(x.publicNameConsent&&x.name?x.name:t("anonymous"))+" · "+String(x.eventCount||0)+" "+(L.ui?.[lang]?.events||"events");c.append(id,meta);w.append(c)})}
function render(d,supporters){state=d;const c=d.campaign||{},m=compute(d),lc=localeContent(c);fillLanguages(c);applyLanguage();document.title=(lc.title||c.title||"Solidarity Fund");$("brandCampaign").textContent=lc.title||c.title||"Solidarity Fund";const pref={fr:"POUR ",de:"FÜR ",es:"PARA ",it:"PER ",pt:"PARA ",nl:"VOOR ",ar:"من أجل "};$("campaignKicker").textContent=c.beneficiary?(pref[lang]||"FOR ")+c.beneficiary:"SOLIDARITY";$("campaignTitle").textContent=lc.subtitle||c.subtitle||lc.title||c.title||"";const closed=["closed","archived"].includes(c.status);$("campaignStory").textContent=closed?(lc.thankYou||c.thankYou_en||lc.story||c.story_en||""):(lc.story||c.story_en||"");$("campaignStatus").textContent=statusLabel(c.status);$("lastUpdated").textContent=dateFmt(d.updated);$("raisedTotal").textContent=euro(m.net/100);$("goalText").textContent=euro(m.target/100);$("progressPct").textContent=Math.round(m.pct)+"%";$("supporterCount").textContent=(supporters||[]).length||m.rows.length;$("remainingAmount").textContent=euro(Math.max(0,m.target-m.net)/100);$("progressLine").style.width=m.pct+"%";
 const url=c.paymentUrl||C.paypalPoolUrl||"https://www.paypal.com/pool/9tfV5v7iJ3",label=lc.paymentLabel||c.paymentLabel_en||t("payWithPayPal"),paymentsClosed=["draft","closed","archived"].includes(c.status);["heroPayBtn","mobilePayBtn","qrPayLink"].forEach(id=>{const a=$(id);if(a)a.href=url});$("paymentLabel").textContent=label;$("mobilePaymentLabel").textContent=label;$("heroPayBtn").classList.toggle("hidden",paymentsClosed);$("mobilePayBtn").classList.toggle("hidden",paymentsClosed);$("qrBtn").classList.toggle("hidden",paymentsClosed);renderMilestones(d,m);renderSupporters(supporters);$("footerCampaign").textContent=(lc.title||c.title||"Solidarity")+" · "+statusLabel(c.status);requestAnimationFrame(drawCurve)}
async function refresh(){const [d,s]=await Promise.all([rpc("karen_public_state"),rpc("solidarity_public_supporters")]);render(d,Array.isArray(s)?s:[])}
function loadQR(){return new Promise((resolve,reject)=>{if(window.QRCode)return resolve();const s=document.createElement("script");s.src="https://cdn.jsdelivr.net/npm/qrcode@1.5.4/build/qrcode.min.js";s.onload=resolve;s.onerror=reject;document.head.append(s)})}
async function showQR(){const dlg=$("qrDialog"),mount=$("qrMount"),url=$("heroPayBtn").href;dlg.showModal();mount.textContent="";try{await loadQR();const canvas=document.createElement("canvas");mount.append(canvas);await QRCode.toCanvas(canvas,url,{width:300,margin:1,color:{dark:"#111015",light:"#ffffff"}});$("qrPayLink").textContent=url.replace("https://www.","")}catch{mount.textContent=url}}
$("qrBtn").onclick=showQR;$("qrClose").onclick=()=>$("qrDialog").close();$("languageSelect").onchange=e=>{lang=e.target.value;localStorage.setItem("solidarity_lang",lang);refresh()};window.addEventListener("resize",()=>requestAnimationFrame(drawCurve));
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));
refresh();setInterval(refresh,30000);
})();