(()=> {
const C=window.KAREN_SUPABASE,L=window.SOLIDARITY_LOCALES,$=id=>document.getElementById(id);
let lang=localStorage.getItem('solidarity_lang')||navigator.language.split('-')[0],state=null,supporters=[],page=0,refreshing=false,qrLoading;
const t=k=>L.ui?.[lang]?.[k]||L.ui?.en?.[k]||k;
const euro=n=>new Intl.NumberFormat(lang,{style:'currency',currency:'EUR',minimumFractionDigits:Number.isInteger(Number(n||0))?0:2,maximumFractionDigits:2}).format(Number(n||0));
const dateFmt=v=>v?new Intl.DateTimeFormat(lang,{day:'numeric',month:'short',year:'numeric'}).format(new Date(String(v).slice(0,10)+'T12:00:00Z')):'—';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
async function rpc(name){const r=await fetch(C.url+'/rest/v1/rpc/'+name,{method:'POST',headers:{'Content-Type':'application/json',apikey:C.key},body:'{}',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('request_failed');return r.json()}
function compute(d){const rows=(d.contributions||[]).filter(x=>['confirmed','received','refunded'].includes(x.status)),pos=rows.filter(x=>x.status!=='refunded'),gross=pos.reduce((s,x)=>s+Number(x.amountCents||0),0),refunds=rows.filter(x=>x.status==='refunded').reduce((s,x)=>s+Number(x.amountCents||0),0),net=gross-refunds,target=Number(d.campaign?.targetCents||0),spent=(d.expenses||[]).reduce((s,x)=>s+Number(x.amountCents||0),0);return{rows,pos,gross,refunds,net,target,spent,available:net-spent,pct:target?Math.max(0,Math.min(100,net/target*100)):0}}
function fillLanguages(c){const enabled=c.enabledLocales?.length?c.enabledLocales:['en','fr'];if(!enabled.includes(lang))lang=enabled.includes('en')?'en':enabled[0];const sel=$('languageSelect');sel.replaceChildren();enabled.forEach(code=>{const o=document.createElement('option');o.value=code;o.textContent=L.names[code]||code.toUpperCase();o.selected=code===lang;sel.append(o)})}
function applyLanguage(){document.documentElement.lang=lang;document.documentElement.dir=(L.rtl||[]).includes(lang)?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));$('supporterSearch').placeholder=t('findSupporter');$('supporterSearch').setAttribute('aria-label',t('findSupporter'))}
function drawCurve(){
 if(!state)return;
 const canvas=$('campaignCurve'),rect=canvas.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1),w=Math.max(300,Math.round(rect.width)),h=Math.max(220,Math.round(rect.height));canvas.width=w*dpr;canvas.height=h*dpr;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);
 const m=compute(state),grouped=new Map();m.rows.forEach(x=>{const day=String(x.date).slice(0,10);grouped.set(day,(grouped.get(day)||0)+(x.status==='refunded'?-1:1)*Number(x.amountCents||0))});
 const days=[...grouped.keys()].sort(),start=Date.parse((days[0]||today())+'T12:00:00Z'),end=Date.parse((days.at(-1)||today())+'T12:00:00Z'),pad={l:w<450?58:70,r:24,t:44,b:38},iw=w-pad.l-pad.r,ih=h-pad.t-pad.b;let total=0;const points=days.map(day=>({day,value:(total+=grouped.get(day))}));
 const max=Math.max(m.target,...points.map(x=>x.value),100),min=Math.min(0,...points.map(x=>x.value)),sx=day=>days.length<2?pad.l+iw/2:pad.l+(Date.parse(day+'T12:00:00Z')-start)/Math.max(1,end-start)*iw,sy=v=>pad.t+ih-(v-min)/(max-min)*ih;
 ctx.clearRect(0,0,w,h);ctx.font='12px system-ui';ctx.textBaseline='middle';for(let i=0;i<=4;i++){const v=min+(max-min)*i/4,y=sy(v);ctx.strokeStyle='#e0e6ee';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();ctx.fillStyle='#59677b';ctx.textAlign='right';ctx.fillText(euro(v/100),pad.l-8,y)}
 if(m.target){const y=sy(m.target);ctx.strokeStyle='#b07808';ctx.lineWidth=2;ctx.setLineDash([7,5]);ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#8f6006';ctx.textAlign='left';ctx.fillText(t('goal')+' '+euro(m.target/100),pad.l,y-14)}
 $('curveNow').textContent=euro(m.net/100);if(!points.length)return;
 const pts=points.map(p=>[sx(p.day),sy(p.value)]),grad=ctx.createLinearGradient(0,pad.t,0,pad.t+ih);grad.addColorStop(0,'rgba(50,106,220,.27)');grad.addColorStop(1,'rgba(50,106,220,.02)');
 const trace=()=>{ctx.moveTo(pts[0][0],pts[0][1]);for(let i=1;i<pts.length;i++){const [x0,y0]=pts[i-1],[x1,y1]=pts[i],mx=(x0+x1)/2;ctx.bezierCurveTo(mx,y0,mx,y1,x1,y1)}};
 ctx.beginPath();trace();ctx.lineTo(pts.at(-1)[0],sy(0));ctx.lineTo(pts[0][0],sy(0));ctx.closePath();ctx.fillStyle=grad;ctx.fill();ctx.beginPath();trace();ctx.strokeStyle='#326adc';ctx.lineWidth=4;ctx.lineCap='round';ctx.stroke();pts.forEach(([x,y],i)=>{ctx.beginPath();ctx.arc(x,y,4,0,2*Math.PI);ctx.fillStyle='white';ctx.fill();ctx.strokeStyle='#326adc';ctx.lineWidth=2;ctx.stroke();if(i===0||i===pts.length-1){ctx.fillStyle='#59677b';ctx.textAlign=i===0?'left':'right';ctx.fillText(dateFmt(points[i].day),x,h-16)}})
}
function milestoneLabel(x){if(lang==='fr'&&x.label_fr)return x.label_fr;if(x.label_en==='Halfway there')return t('halfway');if(x.label_en==='Goal reached')return t('goalReached');return x.label_en||t('milestones')}
function renderMilestones(d,m){const sec=$('campaignMilestones'),wrap=$('milestoneLine'),rows=d.milestones||[];sec.classList.toggle('hidden',!rows.length||d.campaign?.showMilestones===false);wrap.replaceChildren();rows.forEach(x=>{const v=Number(x.thresholdCents||0),p=v?Math.max(0,Math.min(100,m.net/v*100)):0,c=document.createElement('article');c.className='campaign-milestone'+(m.net>=v?' reached':'');const a=document.createElement('strong'),b=document.createElement('span'),bar=document.createElement('div'),fill=document.createElement('i');a.textContent=milestoneLabel(x);b.textContent=euro(v/100)+' · '+(m.net>=v?t('goalReached'):Math.round(p)+'%');bar.className='bar';fill.style.width=p+'%';bar.append(fill);c.append(a,b,bar);wrap.append(c)})}
function renderSupporters(){
 const w=$('supporterSummary'),nav=$('supporterPagination'),q=$('supporterSearch').value.trim().toLowerCase(),list=supporters.filter(x=>(x.supporterId+' '+(x.publicNameConsent?x.name||'':'')).toLowerCase().includes(q)).slice().sort((a,b)=>String(a.supporterId).localeCompare(String(b.supporterId))),pages=Math.max(1,Math.ceil(list.length/12));page=Math.min(page,pages-1);w.replaceChildren();nav.replaceChildren();
 if(!list.length){const p=document.createElement('p');p.textContent=t('noSupporters');w.append(p)}
 list.slice(page*12,page*12+12).forEach(x=>{const c=document.createElement('div');c.className='supporter-id';const id=document.createElement('b'),meta=document.createElement('span');id.textContent=x.supporterId;meta.textContent=(x.publicNameConsent&&x.name?x.name:t('anonymous'))+' · '+String(x.eventCount||0)+' '+t('contributionRecords');c.append(id,meta);w.append(c)});
 if(pages>1){const prev=document.createElement('button'),next=document.createElement('button'),info=document.createElement('span');prev.type=next.type='button';prev.textContent=t('previous');next.textContent=t('next');prev.disabled=page===0;next.disabled=page>=pages-1;prev.onclick=()=>{page--;renderSupporters()};next.onclick=()=>{page++;renderSupporters()};info.textContent=(page+1)+' / '+pages;info.setAttribute('aria-live','polite');nav.append(prev,info,next)}
}
function maybeCelebrate(d,m){const key='solidarity_seen_net_'+d.campaign?.id,prevRaw=localStorage.getItem(key);localStorage.setItem(key,String(m.net));if(prevRaw===null||m.net<=(Number(prevRaw)||0))return;const crossed=(d.milestones||[]).filter(x=>Number(x.thresholdCents)>(Number(prevRaw)||0)&&Number(x.thresholdCents)<=m.net).sort((a,b)=>a.thresholdCents-b.thresholdCents);if(!crossed.length)return;
 let overlay=$('milestoneCelebration');if(!overlay){overlay=document.createElement('dialog');overlay.id='milestoneCelebration';const title=document.createElement('h2'),p=document.createElement('p'),b=document.createElement('button');b.type='button';b.onclick=()=>overlay.close();overlay.append(title,p,b);document.body.append(overlay)}overlay.querySelector('h2').textContent=milestoneLabel(crossed.at(-1));overlay.querySelector('p').textContent=euro(Number(crossed.at(-1).thresholdCents)/100)+' · '+Math.round(m.pct)+'%';overlay.querySelector('button').textContent=t('continue');if(!overlay.open)overlay.showModal()
}
function render(d,s){
 const raw=d.campaign||{};fillLanguages(raw);applyLanguage();const ended=raw.endDate&&today()>raw.endDate&&['active','goal_reached'].includes(raw.status),c={...raw,status:ended?'closed':raw.status};state={...d,campaign:c};supporters=s||[];
 const m=compute(state),lc=c.localeContent?.[lang]||c.localeContent?.en||{};document.title=(lc.title||c.title)+' · The Red Banner';$('brandCampaign').textContent=lc.title||c.title;$('campaignTitle').textContent=lc.title||c.title;$('campaignKicker').textContent=lc.subtitle||c.subtitle||t('solidarity');const closed=['closed','archived'].includes(c.status);$('campaignStory').textContent=closed?(lc.thankYou||lc.story||c.story_en):(lc.story||c.story_en||'');const status=t('status_'+c.status);$('campaignStatus').textContent=status;$('lastUpdated').textContent=dateFmt(d.updated);$('raisedTotal').textContent=euro(m.net/100);$('goalText').textContent=euro(m.target/100);$('progressPct').textContent=Math.round(m.pct)+'%';$('supporterCount').textContent=String(supporters.length||new Set(m.pos.map(x=>x.supporterId||x.id)).size);$('remainingAmount').textContent=euro(Math.max(0,m.target-m.net)/100);$('progressLine').style.width=m.pct+'%';$('progressLine').parentElement.setAttribute('aria-valuenow',String(Math.round(m.pct)));document.body.classList.toggle('goal-reached',m.pct>=100);
 $('campaignDeadline').classList.toggle('hidden',!c.endDate);if(c.endDate){$('deadlineDate').textContent=new Intl.DateTimeFormat(lang,{day:'numeric',month:'long',year:'numeric'}).format(new Date(c.endDate+'T12:00:00Z'));const days=Math.round((Date.parse(c.endDate+'T12:00:00Z')-Date.parse(today()+'T12:00:00Z'))/86400000);$('deadlineCountdown').textContent=closed?t('status_closed'):days===0?t('lastDay'):days+' '+t('daysRemaining')}
 const url=c.paymentUrl||C.paypalPoolUrl,label=lc.paymentLabel||t('payWithPayPal'),paymentsClosed=['draft','closed','archived'].includes(c.status);['heroPayBtn','mobilePayBtn','qrPayLink'].forEach(id=>$(id).href=url);$('paymentLabel').textContent=label;$('mobilePaymentLabel').textContent=label;['heroPayBtn','mobilePayBtn','qrBtn'].forEach(id=>$(id).classList.toggle('hidden',paymentsClosed));$('campaignSupporters').classList.toggle('hidden',c.showSupporters===false);renderMilestones(state,m);renderSupporters();maybeCelebrate(state,m);$('footerCampaign').textContent=(lc.title||c.title)+' · '+status;$('connectionStatus').classList.remove('stale');$('connectionStatus').textContent=t('autoUpdated');window.RBCampaignState={data:state,supporters,metrics:m,lang,euro,dateFmt,t};window.dispatchEvent(new CustomEvent('rb:campaign-data',{detail:window.RBCampaignState}));requestAnimationFrame(drawCurve)
}
async function refresh(){if(refreshing)return;refreshing=true;try{const [d,s]=await Promise.all([rpc('karen_public_state'),rpc('solidarity_public_supporters')]);if(!d?.campaign)throw Error('campaign_unavailable');render(d,Array.isArray(s)?s:[])}catch{$('connectionStatus').classList.add('stale');$('connectionStatus').textContent=t(state?'connectionRetry':'connectionError');if(!state){$('campaignStory').textContent=t('connectionError');['raisedTotal','goalText','remainingAmount','supporterCount'].forEach(id=>$(id).textContent='—')}}finally{refreshing=false}}
function loadQR(){if(window.QRCode)return Promise.resolve();if(qrLoading)return qrLoading;qrLoading=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='./assets/qrcode.min.js';s.onload=resolve;s.onerror=()=>{qrLoading=null;s.remove();reject(Error('qr_unavailable'))};document.head.append(s)});return qrLoading}
async function showQR(){const dlg=$('qrDialog'),mount=$('qrMount'),url=$('heroPayBtn').href;dlg.showModal();mount.replaceChildren();try{await loadQR();new QRCode(mount,{text:url,width:280,height:280,correctLevel:QRCode.CorrectLevel.M});$('qrPayLink').textContent=t('payWithPayPal')}catch{mount.textContent=url}}
$('qrBtn').onclick=showQR;$('qrClose').onclick=()=>$('qrDialog').close();$('supporterSearch').oninput=()=>{page=0;renderSupporters()};$('languageSelect').onchange=e=>{lang=e.target.value;localStorage.setItem('solidarity_lang',lang);if(state)render(state,supporters);else{applyLanguage();refresh()}};window.addEventListener('resize',()=>requestAnimationFrame(drawCurve));
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));window.refreshKarenFund=refresh;refresh();setInterval(()=>{if(!document.hidden)refresh()},30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});
})();
