(()=>{'use strict';const t=s=>window.RBLocale?.t(s)||s,tools=window.RBCalendarTools;let events=[],saved=[];try{saved=JSON.parse(localStorage.getItem('rb-saved-plans')||'[]')}catch{}const el=(tag,text,cls)=>{const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n};
const dateLabel=s=>new Intl.DateTimeFormat(window.RBLocale?.locale||'en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'Europe/Berlin'}).format(new Date(s+'T12:00:00Z'));
const dialog=document.createElement('dialog');dialog.className='calendar-dialog';dialog.id='calendarDialog';dialog.setAttribute('aria-labelledby','calendarTitle');dialog.innerHTML='<header><div><p class="eyebrow">MAKE ROOM FOR THE COLLECTIVE</p><h2 id="calendarTitle">Add to your calendar</h2></div><button class="icon-btn" data-close-calendar aria-label="Close calendar options">×</button></header><div class="calendar-content"><h3 data-calendar-title translate="no"></h3><p data-calendar-date></p><div class="calendar-options"></div><label class="calendar-reminder">Reminder for calendar file<select data-reminder><option value="120">2 hours before</option><option value="30">30 minutes before</option><option value="1440">1 day before</option><option value="0">No reminder</option></select></label><p class="calendar-note">Google and Outlook use their own reminder settings. Imported copies do not update automatically. Follow the event here for changes.</p><p data-calendar-result role="status"></p></div>';document.body.append(dialog);dialog.querySelector('[data-close-calendar]').onclick=()=>dialog.close();
function download(list,reminder){const blob=new Blob([tools.ics(list,reminder)],{type:'text/calendar;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=list.length===1?'red-banner-'+list[0].id+'.ics':'red-banner-agenda.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
function open(e){let d;try{d=tools.details(e)}catch(err){return}const links=tools.links(e),root=dialog.querySelector('.calendar-options');root.replaceChildren();dialog.querySelector('[data-calendar-title]').textContent=e.title;dialog.querySelector('[data-calendar-date]').textContent=dateLabel(e.date)+' · '+(d.timed?e.time+' · Europe/Berlin':t('Time to be confirmed · all-day placeholder'));dialog.querySelector('[data-calendar-result]').textContent='';for(const [label,key,mark]of [['Google Calendar','google','G'],['Outlook.com','outlook','O'],['Microsoft 365','office','M']]){const a=el('a','','calendar-option');a.href=links[key];a.target='_blank';a.rel='noopener noreferrer';const icon=el('span',mark,'calendar-provider '+key);icon.setAttribute('aria-hidden','true');a.append(icon,el('span',label),el('span','↗'));root.append(a)}for(const label of ['Apple Calendar','Other calendar · .ics file']){const b=el('button','','calendar-option');b.type='button';b.append(el('span','▦','calendar-provider apple'),el('span',t(label)),el('span','↓'));b.onclick=()=>{download([e],Number(dialog.querySelector('[data-reminder]').value));dialog.querySelector('[data-calendar-result]').textContent=t('Calendar file ready. Open it with your calendar app and confirm the import.');};root.append(b)}if(!dialog.open)dialog.showModal()}
const section=el('section','','personal-agenda');section.innerHTML='<div class="section-heading"><div><p class="eyebrow">YOUR CORNER OF THE COMMONS</p><h2>Keep your plans together.</h2></div><button class="text-link" data-export-plans>Export saved agenda ↓</button></div><p class="subtle">Save a plan from its details. Your shortlist stays on this device.</p><div data-saved-plans></div><p data-agenda-result class="form-status" role="status"></p>';document.querySelector('.solidarity-stage')?.after(section);
function render(){const mount=section.querySelector('[data-saved-plans]');mount.replaceChildren();const list=events.filter(e=>saved.includes(e.id)).sort((a,b)=>a.date.localeCompare(b.date));section.querySelector('[data-export-plans]').disabled=!list.some(e=>e.date&&!['cancelled','postponed'].includes(e.status));if(!list.length){const p=el('p',t('A training session, a shared meal, a day outside. Make space for what matters.'),'saved-empty');mount.append(p)}for(const e of list){const row=el('article','','saved-plan tone-'+e.category),date=el('span',e.date?dateLabel(e.date):t('Date to be decided'),'saved-date'),button=el('button',e.title,'text-link');button.setAttribute('translate','no');button.onclick=()=>window.RBCommunity.openEvent(e.id);const remove=el('button','×','icon-btn');remove.setAttribute('aria-label',t('Remove saved plan')+': '+e.title);remove.onclick=()=>save(e.id,false);row.append(date,button,remove);if(['cancelled','postponed'].includes(e.status))row.append(el('span',t(e.status==='cancelled'?'Cancelled':'Postponed'),'status-chip'));mount.append(row)}}
function save(id,on){saved=on?[...new Set([...saved,id])]:saved.filter(x=>x!==id);try{localStorage.setItem('rb-saved-plans',JSON.stringify(saved))}catch{section.querySelector('[data-agenda-result]').textContent=t('Browser storage unavailable. Plans are saved for this visit only.')}render()}
section.querySelector('[data-export-plans]').onclick=()=>{const list=events.filter(e=>saved.includes(e.id)&&e.date&&!['cancelled','postponed'].includes(e.status));if(list.length){download(list,120);section.querySelector('[data-agenda-result]').textContent=t('Saved agenda exported. Cancelled, postponed and undated plans are excluded.')}};
window.RBCalendar={open,attach(root,e){const row=el('div','','plan-utilities'),button=el('button',t(saved.includes(e.id)?'Saved to my agenda':'Save to my agenda'),'btn outline');button.setAttribute('aria-pressed',saved.includes(e.id));button.onclick=()=>{save(e.id,!saved.includes(e.id));button.textContent=t(saved.includes(e.id)?'Saved to my agenda':'Save to my agenda');button.setAttribute('aria-pressed',saved.includes(e.id))};row.append(button);if(e.address){const a=el('a',t('Get directions ↗'),'text-link');a.href='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(e.address);a.target='_blank';a.rel='noopener noreferrer';row.append(a)}root.append(row)}};
window.addEventListener('rb-events-loaded',e=>{events=e.detail;render()});window.addEventListener('rb-language-change',render);window.addEventListener('rb-language-ready',render);render();
})();
