/* Opt-in delivery. Device capabilities never enter URLs or notification payloads. */
(()=>{'use strict';
const endpoint='https://btygzxeyesnaxljfciqv.supabase.co/functions/v1/red-banner-notifications';
const root=document.querySelector('#notificationsDialog .alert-settings');if(!root)return;
const get=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},t=s=>window.RBLocale?.t(s)||s;
let credentials=get('rb-delivery-device',null),registered=false,config=null,state={},quietStart=22,quietEnd=8;
const panel=document.createElement('section');panel.className='delivery-card background-delivery';
panel.innerHTML=`<span class="delivery-status">OPT IN · STAY CONNECTED</span><h4>Beyond the browser tab.</h4><p>Receive announcements, changes to followed events and private-reply alerts. Message contents stay private.</p><p data-delivery-status role="status" aria-live="polite">Checking delivery services…</p><button class="btn outline" data-push disabled>Enable background push</button><button class="text-link" data-test hidden>Send me a test notification</button><p class="subtle">On iPhone, add this app to your Home Screen, open it there, then enable notifications.</p><div class="quiet-hours"><label>Quiet hours start<select data-quiet-start></select></label><label>Quiet hours end<select data-quiet-end></select></label></div><p class="subtle">Berlin time. Choose the same hour to turn quiet hours off.</p><button class="text-link" data-save disabled>Save delivery preferences</button><hr><h4>SMS & WhatsApp</h4><p data-phone-status>Sender setup required. Automatic phone notifications are not active.</p><form data-phone hidden><label>Phone number<input name="phone" type="tel" autocomplete="tel" placeholder="+49…" required pattern="\\+[1-9][0-9]{7,14}"></label><label><input type="checkbox" name="sms">I agree to receive SMS notifications.</label><label><input type="checkbox" name="whatsapp">I agree to receive WhatsApp notifications.</label><p>Verification sends one SMS. You can unsubscribe here or reply STOP.</p><div data-captcha></div><button class="btn outline" type="submit">Send verification code</button><label data-code hidden>Verification code<input name="code" inputmode="numeric" autocomplete="one-time-code" maxlength="10"></label></form><button class="text-link" data-phone-off hidden>Disable phone notifications</button><button class="text-link" data-delete hidden>Remove all delivery subscriptions</button>`;
root.querySelectorAll('.delivery-card').forEach(n=>n.hidden=true);root.insertBefore(panel,root.querySelector('[data-alert-clear]'));
const $=s=>panel.querySelector(s),say=s=>$('[data-delivery-status]').textContent=t(s);
for(const [selector,hour]of [['[data-quiet-start]',22],['[data-quiet-end]',8]]){for(let h=0;h<24;h++){const o=new Option(String(h).padStart(2,'0')+':00',h);$(selector).append(o)}$(selector).value=hour}
const prefs=()=>({official:get('rb-alert-prefs',{}).official!==false,replies:get('rb-alert-prefs',{}).replies!==false,events:Object.keys(get('rb-event-follows',{})),language:window.RBLocale?.language||'en',quietStart:Number($('[data-quiet-start]').value),quietEnd:Number($('[data-quiet-end]').value)});
async function api(action,data={}){const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...credentials,action,...data}),signal:AbortSignal.timeout(20000)});const result=await r.json();if(!r.ok)throw Error(result.error||'Delivery service unavailable.');return result}
function identity(){if(!credentials){credentials={id:crypto.randomUUID(),token:[...crypto.getRandomValues(new Uint8Array(32))].map(b=>b.toString(16).padStart(2,'0')).join('')};try{localStorage.setItem('rb-delivery-device',JSON.stringify(credentials))}catch{credentials=null;throw Error('Enable browser storage before subscribing.')}}}
async function bind(){for(const c of get('rb-private-conversations',[]).slice(-20))await api('bind',{thread:c.id,threadToken:c.token})}
async function sync(){if(!registered)return;try{await api('preferences',{preferences:prefs()});await bind()}catch(e){say(e.message)}}
window.RBDelivery={sync};
function render(){const supported='Notification'in window&&'serviceWorker'in navigator&&'PushManager'in window;$('[data-push]').disabled=!supported||!config?.push;$('[data-push]').textContent=t(state.push?'Disable background push':'Enable background push');$('[data-test]').hidden=!state.push;$('[data-delete]').hidden=!registered;$('[data-save]').disabled=!registered;$('[data-phone-off]').hidden=!(state.sms||state.whatsapp);if(state.push)window.dispatchEvent(new Event('rb-background-connected'));}
async function refresh(){state=await api('status');registered=true;quietStart=state.preferences.quietStart;quietEnd=state.preferences.quietEnd;$('[data-quiet-start]').value=quietStart;$('[data-quiet-end]').value=quietEnd;render()}
$('[data-push]').onclick=async()=>{const button=$('[data-push]');button.disabled=true;try{if(state.push){await api('unsubscribe',{channel:'push'});const reg=await navigator.serviceWorker.ready;await (await reg.pushManager.getSubscription())?.unsubscribe();await refresh();say('Background push disabled.');return}const permission=await Notification.requestPermission();if(permission!=='granted')throw Error('Permission was not granted. Change notification permission in browser settings.');identity();await navigator.serviceWorker.register('./sw.js');const reg=await navigator.serviceWorker.ready;const key=Uint8Array.from(atob(config.publicKey.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));let sub=await reg.pushManager.getSubscription();let created=false;if(!sub){sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key});created=true}try{await api('register',{subscription:sub.toJSON(),preferences:prefs()})}catch(e){if(created)await sub.unsubscribe();throw e}await refresh();await bind();say('Background push enabled. Delivery can take a few minutes.')}catch(e){say(e.message)}finally{render()}};
$('[data-test]').onclick=async()=>{try{await api('test');say('Test queued. Allow a few minutes for delivery.')}catch(e){say(e.message)}};
$('[data-save]').onclick=async()=>{try{await api('preferences',{preferences:prefs()});await bind();say('Delivery preferences saved.')}catch(e){say(e.message)}};
$('[data-phone-off]').onclick=async()=>{try{await api('unsubscribe',{channel:'sms'});await api('unsubscribe',{channel:'whatsapp'});await refresh();say('Phone notifications disabled.')}catch(e){say(e.message)}};
$('[data-delete]').onclick=async()=>{try{await api('unsubscribe',{channel:'all'});if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.getRegistration();await (await reg?.pushManager?.getSubscription())?.unsubscribe()}localStorage.removeItem('rb-delivery-device');credentials=null;registered=false;state={};render();say('All delivery subscriptions removed.')}catch(e){say(e.message)}};
let captcha='',verification=null;
async function phoneUI(){if(!(config.sms||config.whatsapp))return;$('[data-phone-status]').textContent=t('Choose your channels and verify your number.');const form=$('[data-phone]');form.hidden=false;form.elements.sms.disabled=!config.sms;form.elements.whatsapp.disabled=!config.whatsapp;window.rbTurnstileReady=()=>window.turnstile.render($('[data-captcha]'),{sitekey:config.turnstileSiteKey,callback:token=>captcha=token,'expired-callback':()=>captcha=''});const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?onload=rbTurnstileReady&render=explicit';script.async=true;script.onerror=()=>say('Verification challenge unavailable. Please try later.');document.head.append(script);
form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button');button.disabled=true;try{if(!registered){identity();await api('register',{subscription:null,preferences:prefs()});registered=true}const data={phone:form.elements.phone.value.trim(),sms:form.elements.sms.checked,whatsapp:form.elements.whatsapp.checked,consent:form.elements.sms.checked||form.elements.whatsapp.checked};if(verification){if(JSON.stringify(data)!==JSON.stringify(verification))throw Error('Keep the number and channels unchanged until verification finishes.');await api('phone-finish',{...data,code:form.elements.code.value.trim()});verification=null;form.reset();$('[data-code]').hidden=true;button.textContent=t('Send verification code');await refresh();say('Phone notifications enabled.')}else{await api('phone-start',{...data,captcha});verification=data;$('[data-code]').hidden=false;button.textContent=t('Verify and enable');say('Verification SMS sent. Enter the code.')}}catch(e){say(e.message)}finally{button.disabled=false}}}
window.addEventListener('rb-language-change',()=>{render();sync()});
(async()=>{try{const r=await fetch(endpoint,{signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Delivery service unavailable.');config=await r.json();if(credentials){try{await refresh()}catch{registered=false;say('Saved subscription could not be verified. Try again later.')}}if(!registered)say(config.push?'Choose the notifications you want.':'Background delivery is awaiting scheduler activation.');render();await phoneUI()}catch(e){say(e.message)}})();
})();
