(()=>{
const keys=['trainingNav','fundraisingUntil','birthdayNote','daysRemaining','lastDay','chartPeriod','allTime','last7Days','last30Days','exportData','exportPlot','goalPosition','shareCampaign','shared','findSupporter','noSupporters','previous','next','contributionRecords','halfway','continue','connectionRetry','connectionError','campaignCurveText','manualSource','paypalPoolSource','paypalSource','rollingAverage','status_active','status_goal_reached','status_closed','status_archived','status_draft','trainingDirections','calendar','shareEvent'];
const rows={
en:['Training','Fundraising until','Before Karen’s birthday on 23 October.','days remaining','Final day','Plot period','All time','Last 7 days','Last 30 days','Export public data','Save plot','Raised and remaining','Share campaign','Link copied','Find a supporter ID','No matching supporters','Previous','Next','contributions','Halfway there','Continue','Showing saved data · retrying','Unable to load live data · retrying shortly','Confirmed contributions over time. The dashed line is the goal.','Manual / bank / cash','PayPal Pool','PayPal','3-day mean','LIVE','GOAL REACHED','CLOSED','ARCHIVED','DRAFT','Directions','Add to calendar','Share training'],
fr:['Entraînement','Collecte jusqu’au','Avant l’anniversaire de Karen, le 23 octobre.','jours restants','Dernier jour','Période','Depuis le début','7 derniers jours','30 derniers jours','Exporter les données publiques','Enregistrer','Collecté et restant','Partager la campagne','Lien copié','Rechercher un ID de soutien','Aucun soutien correspondant','Précédent','Suivant','contributions','Mi-parcours','Continuer','Données conservées · reconnexion','Données indisponibles · nouvelle tentative bientôt','Contributions confirmées au fil du temps. La ligne pointillée indique l’objectif.','Manuel / banque / espèces','Cagnotte PayPal','PayPal','Moyenne sur 3 jours','EN DIRECT','OBJECTIF ATTEINT','CLÔTURÉE','ARCHIVÉE','BROUILLON','Itinéraire','Ajouter au calendrier','Partager l’entraînement'],
de:['Training','Spenden bis','Vor Karens Geburtstag am 23. Oktober.','Tage verbleibend','Letzter Tag','Zeitraum','Gesamter Zeitraum','Letzte 7 Tage','Letzte 30 Tage','Öffentliche Daten exportieren','Diagramm speichern','Gesammelt und verbleibend','Kampagne teilen','Link kopiert','Unterstützer-ID suchen','Keine passenden Unterstützenden','Zurück','Weiter','Beiträge','Halbzeit','Weiter','Gespeicherte Daten · erneuter Versuch','Live-Daten nicht verfügbar · erneuter Versuch folgt','Bestätigte Beiträge im Zeitverlauf. Die gestrichelte Linie zeigt das Ziel.','Manuell / Bank / Bargeld','PayPal-Sammelaktion','PayPal','3-Tage-Mittel','LIVE','ZIEL ERREICHT','BEENDET','ARCHIVIERT','ENTWURF','Anfahrt','Zum Kalender hinzufügen','Training teilen'],
es:['Entrenamiento','Recaudación hasta el','Antes del cumpleaños de Karen, el 23 de octubre.','días restantes','Último día','Período','Todo el período','Últimos 7 días','Últimos 30 días','Exportar datos públicos','Guardar gráfico','Recaudado y restante','Compartir campaña','Enlace copiado','Buscar un ID de apoyo','No hay apoyos coincidentes','Anterior','Siguiente','contribuciones','A mitad de camino','Continuar','Datos guardados · reintentando','Datos no disponibles · se reintentará pronto','Contribuciones confirmadas en el tiempo. La línea discontinua indica la meta.','Manual / banco / efectivo','Fondo de PayPal','PayPal','Media de 3 días','EN VIVO','META ALCANZADA','CERRADA','ARCHIVADA','BORRADOR','Cómo llegar','Añadir al calendario','Compartir entrenamiento'],
it:['Allenamento','Raccolta fino al','Prima del compleanno di Karen, il 23 ottobre.','giorni rimanenti','Ultimo giorno','Periodo','Dall’inizio','Ultimi 7 giorni','Ultimi 30 giorni','Esporta dati pubblici','Salva grafico','Raccolto e rimanente','Condividi campagna','Link copiato','Cerca un ID sostenitore','Nessun sostenitore corrispondente','Precedente','Successivo','contributi','A metà strada','Continua','Dati salvati · nuovo tentativo','Dati non disponibili · nuovo tentativo a breve','Contributi confermati nel tempo. La linea tratteggiata indica l’obiettivo.','Manuale / banca / contanti','Fondo PayPal','PayPal','Media di 3 giorni','LIVE','OBIETTIVO RAGGIUNTO','CHIUSA','ARCHIVIATA','BOZZA','Indicazioni','Aggiungi al calendario','Condividi allenamento'],
pt:['Treino','Angariação até','Antes do aniversário de Karen, a 23 de outubro.','dias restantes','Último dia','Período','Desde o início','Últimos 7 dias','Últimos 30 dias','Exportar dados públicos','Guardar gráfico','Arrecadado e restante','Partilhar campanha','Link copiado','Procurar um ID de apoio','Nenhum apoiador correspondente','Anterior','Seguinte','contribuições','A meio caminho','Continuar','Dados guardados · nova tentativa','Dados indisponíveis · nova tentativa em breve','Contribuições confirmadas ao longo do tempo. A linha tracejada indica a meta.','Manual / banco / dinheiro','Fundo PayPal','PayPal','Média de 3 dias','AO VIVO','META ALCANÇADA','ENCERRADA','ARQUIVADA','RASCUNHO','Como chegar','Adicionar ao calendário','Partilhar treino'],
nl:['Training','Inzameling tot','Voor Karens verjaardag op 23 oktober.','dagen over','Laatste dag','Periode','Vanaf het begin','Laatste 7 dagen','Laatste 30 dagen','Openbare data exporteren','Grafiek opslaan','Ingezameld en resterend','Campagne delen','Link gekopieerd','Zoek een supporter-ID','Geen overeenkomende supporters','Vorige','Volgende','bijdragen','Halverwege','Doorgaan','Opgeslagen data · opnieuw proberen','Live data niet beschikbaar · binnenkort opnieuw proberen','Bevestigde bijdragen in de tijd. De stippellijn is het doel.','Handmatig / bank / contant','PayPal-pot','PayPal','3-daags gemiddelde','LIVE','DOEL BEREIKT','GESLOTEN','GEARCHIVEERD','CONCEPT','Route','Toevoegen aan agenda','Training delen'],
ar:['التدريب','جمع التبرعات حتى','قبل عيد ميلاد كارين في 23 أكتوبر.','أيام متبقية','اليوم الأخير','الفترة','منذ البداية','آخر 7 أيام','آخر 30 يومًا','تصدير البيانات العامة','حفظ الرسم','المبلغ المجمع والمتبقي','مشاركة الحملة','تم نسخ الرابط','البحث عن معرّف داعم','لا يوجد داعمون مطابقون','السابق','التالي','مساهمات','منتصف الطريق','متابعة','عرض البيانات المحفوظة · إعادة المحاولة','البيانات غير متاحة · ستتم إعادة المحاولة قريبًا','المساهمات المؤكدة بمرور الوقت. الخط المتقطع يمثل الهدف.','يدوي / بنك / نقدًا','صندوق PayPal','PayPal','متوسط 3 أيام','مباشر','تم بلوغ الهدف','مغلق','مؤرشف','مسودة','الاتجاهات','إضافة إلى التقويم','مشاركة التدريب']
};
for(const [lang,row] of Object.entries(rows))Object.assign(window.SOLIDARITY_LOCALES.ui[lang],Object.fromEntries(keys.map((key,i)=>[key,row[i]])));

const extra={
en:{qr:'Show QR',now:'Now',scanToContribute:'Scan to contribute'},fr:{qr:'Afficher le QR',now:'Maintenant',scanToContribute:'Scanner pour contribuer'},de:{qr:'QR anzeigen',now:'Jetzt',scanToContribute:'Scannen zum Beitragen'},es:{qr:'Mostrar QR',now:'Ahora',scanToContribute:'Escanear para contribuir'},it:{qr:'Mostra QR',now:'Ora',scanToContribute:'Scansiona per contribuire'},pt:{qr:'Mostrar QR',now:'Agora',scanToContribute:'Digitalizar para contribuir'},nl:{qr:'QR tonen',now:'Nu',scanToContribute:'Scan om bij te dragen'},ar:{qr:'عرض رمز QR',now:'الآن',scanToContribute:'امسح للمساهمة'}
};
for(const [lang,values] of Object.entries(extra))Object.assign(window.SOLIDARITY_LOCALES.ui[lang],values);

const targetLabels={
 en:{targetUpdated:'Target updated',previousTarget:'Previously',targetOn:'Updated',targetExplanation:'The contribution total is unchanged.'},
 fr:{targetUpdated:'Objectif actualisé',previousTarget:'Auparavant',targetOn:'Actualisé le',targetExplanation:'Le total des contributions reste inchangé.'},
 de:{targetUpdated:'Ziel aktualisiert',previousTarget:'Bisher',targetOn:'Aktualisiert am',targetExplanation:'Die Beitragssumme bleibt unverändert.'},
 es:{targetUpdated:'Objetivo actualizado',previousTarget:'Anteriormente',targetOn:'Actualizado el',targetExplanation:'El total de contribuciones no cambia.'},
 it:{targetUpdated:'Obiettivo aggiornato',previousTarget:'Prima',targetOn:'Aggiornato il',targetExplanation:'Il totale dei contributi resta invariato.'},
 pt:{targetUpdated:'Meta atualizada',previousTarget:'Anteriormente',targetOn:'Atualizada em',targetExplanation:'O total de contribuições permanece igual.'},
 nl:{targetUpdated:'Doel bijgewerkt',previousTarget:'Voorheen',targetOn:'Bijgewerkt op',targetExplanation:'Het totaal aan bijdragen blijft gelijk.'},
 ar:{targetUpdated:'تم تحديث الهدف',previousTarget:'سابقًا',targetOn:'تم التحديث في',targetExplanation:'إجمالي المساهمات لم يتغير.'}
};
for(const [lang,values] of Object.entries(targetLabels))Object.assign(window.SOLIDARITY_LOCALES.ui[lang],values);
})();
