(()=>{
'use strict';
const $=id=>document.getElementById(id),cfg=window.KAREN_SUPABASE||{},esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}};
const old=read('red-banner-community-preview-v1',{});let name=read('rb-name',old.name||''),device=read('rb-community-device',null);
if(!device){try{device=localStorage.getItem('rb-community-voter')}catch{}}
if(!/^[0-9a-f-]{36}$/i.test(device||''))device=crypto.randomUUID();write('rb-community-device',device);
const money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'EUR',maximumFractionDigits:Number(n)%100===0?0:2}).format(Number(n||0)/100);
const dateLabel=(s,opts={weekday:'short',day:'numeric',month:'short'})=>s?new Intl.DateTimeFormat('en-GB',opts).format(new Date(s.slice(0,10)+'T12:00:00Z')):'Date to be decided';
const stamp=s=>new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(s));
const icon=s=>`<svg class="i" aria-hidden="true"><use href="#i-${s}"/></svg>`;
const types={solidarity:{name:'Solidarity',icon:'flag'},social:{name:'Social & games',icon:'race'},learning:{name:'Ideas & learning',icon:'poll'},food:{name:'Food & brunch',icon:'brunch'},outdoors:{name:'Outdoors & travel',icon:'mountain'}};
const options=['06','07','13','14','20','21','27','28'].map(d=>'2026-11-'+d);
let savedVote=read('rb-vote-saved',[]),draftVote=read('rb-vote-draft',old.myVote||savedVote),posts=[],events=[],poll=[],attendance=[],brunch=[],brunchMode='unknown',sharedReady=false,refreshing=false,toastTimer,activeEvent=null;
let conversations=read('rb-private-conversations',[]),activeConversation=null,pendingConversation=null;
const firstSaturday=(y,m)=>{const d=new Date(Date.UTC(y,m,1));d.setUTCDate(1+(6-d.getUTCDay()+7)%7);return d.toISOString().slice(0,10)};
const now=new Date(),thisBrunch=firstSaturday(now.getFullYear(),now.getMonth()),baseMonth=now.getDate()>Number(thisBrunch.slice(8))?now.getMonth()+1:now.getMonth();
const sessions=Array.from({length:6},(_,i)=>firstSaturday(now.getFullYear(),baseMonth+i));let session=sessions[0];
let training={id:'karen-training',title:'Train together for Karen',date:'2026-10-17',time:'11:30',endTime:'13:30',place:'Functional Garage 0211',address:'In der Hött 8b, 40223 Düsseldorf, Germany',description:'A solidarity training session to support Karen. Pay what you can.',category:'solidarity',status:'scheduled'};
const seedNotes=[{display_name:'Group proposal',body:'Some of us suggested that we should go karting on 24 October. The time and venue are still to be decided. Add your interest and let’s make it happen.',created_at:'2026-10-08T18:00:00Z',kind:'note'},{display_name:'PowerPoint Night',body:'We can meet to eat or train—and we can present the topics that interest us. The reactionaries and evil compradors can keep calling hobbies private: we’ll collectivize our curiosities at PowerPoint Night. Vote for every Friday and Saturday evening in November that works for you.',created_at:'2026-10-08T18:20:00Z',kind:'note'}];
const suggestions=['Something savoury','Fruit or a fruit salad','Bread and spreads','Tea, coffee, or juice','Help with setup or cleanup'];
const ideas=[['Bouldering afternoon','outdoors','Pick a gym, choose a date, and see who wants to climb.'],['Picnic in the park','food','Shared food, a blanket, and a low-cost afternoon outside.'],['A day on the trail','outdoors','Choose a route, a meeting point, and a plan for getting there.'],['Barbecue together','food','Find a grill spot and coordinate food, drinks, and equipment.'],['A weekend away','outdoors','Start with a destination, a budget, and a few possible dates.'],['A skill to share','learning','A workshop, a language exchange, or a passionate ten-minute talk.']];
async function db(path,body,method){
 if(!cfg.url||!cfg.key)throw Error('Connection unavailable. Please try again.');
 const response=await fetch(cfg.url+'/rest/v1/'+path,{method:method||(body===undefined?'GET':'POST'),headers:{apikey:cfg.key,Accept:'application/json',...(body===undefined?{}:{'Content-Type':'application/json',Prefer:'return=minimal'})},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(12000)});
 if(!response.ok){let info={};try{info=await response.json()}catch{}const e=Error(response.status===404||info.code==='PGRST202'?'This feature is awaiting organizer setup. Your message has not been sent.':'Could not save or load this information. Please try again.');e.pending=response.status===404||info.code==='PGRST202';throw e}
 const text=await response.text();return text?JSON.parse(text):null;
}
const rpc=(fn,body={})=>db('rpc/'+fn,body);
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3500)}
function status(id,text,bad=false){$(id).textContent=text;$(id).classList.toggle('error',bad)}
async function submit(form,id,fn){const buttons=[...form.querySelectorAll('button[type="submit"]')];buttons.forEach(b=>b.disabled=true);status(id,'Saving…');try{await fn();return true}catch(e){status(id,e.message||'Could not save. Please try again.',true);return false}finally{buttons.forEach(b=>b.disabled=false)}}
function setView(view){if(!['home','events','polls','brunch','messages','ideas'].includes(view))view='home';document.querySelectorAll('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==view);document.querySelectorAll('[data-view]').forEach(b=>{const on=b.dataset.view===view;b.classList.toggle('active',on);on?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current')});$('currentView').textContent=({home:'Overview',events:'Events',polls:'Polls',brunch:'People’s Brunch',messages:'Community board',ideas:'Ideas & adventures'})[view];if(location.hash!=='#'+view)history.replaceState(null,'','#'+view);$('moreDialog').close();window.scrollTo({top:0,behavior:'instant'})}
function open(id){if(!$(id).open)$(id).showModal()}
function setSync(ok){sharedReady=ok;$('syncDot').style.background=ok?'#168564':'#a0661b';$('syncText').textContent=ok?'Shared with the group':'Connection interrupted';$('mobileSyncText').textContent=ok?'Shared board connected':'Connection interrupted · retrying'}
function buildEvents(){
 events=[{...training},{id:'karting',title:'Karting. Let’s go.',category:'social',date:'2026-10-24',time:'',place:'Venue to be decided',description:'Some of us suggested a day on the track. Add your interest while we settle the time and venue.',status:'proposed'},...sessions.map(d=>({id:'brunch-'+d,title:'People’s Brunch',category:'food',date:d,time:'',place:'Place to be confirmed',description:'First Saturday of the month. Bring something for the table or lend a hand.',status:'scheduled'})),...posts.filter(p=>p.kind==='event-proposal').map(p=>({id:p.id,title:p.metadata?.title||p.body,category:types[p.metadata?.category]?p.metadata.category:'social',date:p.metadata?.date||'',time:p.metadata?.time||'',place:p.metadata?.place||'Place to be decided',description:p.metadata?.description||'',status:'proposed'}))];
 const changed=new Set();posts.filter(p=>p.kind==='event-update').forEach(p=>{let id=p.metadata?.event_id;if(id==='brunch-nov')id='brunch-2026-11-07';const e=events.find(e=>e.id===id);if(e&&!changed.has(id)){e.status=['cancelled','postponed','changed','scheduled'].includes(p.metadata.status)?p.metadata.status:'changed';e.note=p.body;e.updatedBy=p.display_name;e.date=p.metadata.date||e.date;if(p.metadata.time&&p.metadata.time!==e.time)e.endTime='';e.time=p.metadata.time||e.time;changed.add(id)}});
 const featuredTraining=events.find(e=>e.id==='karen-training');$('trainingDay').textContent=featuredTraining.date.slice(8);$('trainingMonth').textContent=dateLabel(featuredTraining.date,{month:'short'}).toUpperCase();$('trainingTime').textContent=(['cancelled','postponed'].includes(featuredTraining.status)?statusLabel(featuredTraining)+' · ':'')+dateLabel(featuredTraining.date,{weekday:'long'})+' · '+featuredTraining.time+(featuredTraining.endTime?'–'+featuredTraining.endTime:'');$('trainingVenue').textContent=featuredTraining.place;$('trainingChange').hidden=!featuredTraining.note;$('trainingChange').textContent=featuredTraining.note||'';
 renderEvents();renderBrunchHeading();
}
function statusLabel(e){return ({cancelled:'Cancelled',postponed:'Postponed',changed:'Updated',proposed:'Proposed',scheduled:'On the calendar'})[e.status]||'Proposed'}
function attendee(e){return attendance.find(a=>a.event_id===e.id)||{going:0,maybe:0,mine:null}}
function card(e){const t=types[e.category],a=attendee(e);return `<article class="event-card tone-${e.category}"><div class="event-card-head"><div class="card-kicker"><span class="category-label">${icon(t.icon)}${esc(t.name)}</span><span class="status-chip ${esc(e.status)}">${statusLabel(e)}</span></div><h3>${esc(e.title)}</h3><p>${esc(dateLabel(e.date))} · ${esc(e.time||'Time TBD')}</p></div><div class="event-card-body"><p class="event-meta">${esc(e.place)}</p><p class="event-desc">${esc(e.description)}</p>${e.note?`<p class="event-update-note">${esc(e.note)}</p>`:''}<div class="event-card-foot"><span class="attendance-small">${a.mine?esc(({going:'You’re going',maybe:'You’re interested',not_going:'You can’t make it'})[a.mine]):`${Number(a.going)} going · ${Number(a.maybe)} interested`}</span><button class="text-link" data-event-open="${esc(e.id)}">View plan →</button></div></div></article>`}
function renderEvents(){
 const q=$('eventSearch').value.toLowerCase(),filter=$('eventFilter').value,mine=$('myEvents').checked;
 const visible=events.filter(e=>e.id.indexOf('brunch-')!==0||e.id==='brunch-'+session).filter(e=>(filter==='all'||e.category===filter)&&(!mine||['going','maybe'].includes(attendee(e).mine))&&`${e.title} ${e.place}`.toLowerCase().includes(q));
 $('eventList').innerHTML=visible.length?visible.map(card).join(''):'<p class="empty">No matching plans. Try another filter or propose an event.</p>';$('eventCount').textContent=String(events.filter(e=>!e.id.startsWith('brunch-')&&e.status!=='cancelled').length+1);
 const kart=events.find(e=>e.id==='karting'),br=events.find(e=>e.id==='brunch-'+session);
 $('featuredEvents').innerHTML=card(kart)+`<article class="event-card tone-learning"><div class="event-card-head"><div class="card-kicker"><span class="category-label">${icon('poll')}IDEAS & LEARNING</span><span class="status-chip">Vote open</span></div><h3>PowerPoint Night</h3><p>Friday & Saturday evenings · November</p></div><div class="event-card-body"><p class="event-meta">One topic. Ten minutes. All our curiosities.</p><p class="event-desc">Help choose a night to share the things we can’t stop thinking about.</p><div class="event-card-foot"><span class="attendance-small">${Number(poll[0]?.total_voters||0)} people voted</span><button class="text-link" data-view="polls">Choose your dates →</button></div></div></article>`+card(br);
}
function openEvent(id){const e=events.find(e=>e.id===id);if(!e)return;activeEvent=id;const a=attendee(e);$('eventDetailContent').innerHTML=`<div class="event-detail tone-${e.category}"><span class="category-label">${icon(types[e.category].icon)}${esc(types[e.category].name)}</span><h2>${esc(e.title)}</h2><span class="status-chip ${esc(e.status)}">${statusLabel(e)}</span><p><strong>${esc(dateLabel(e.date))} · ${esc(e.time||'Time to be confirmed')}${e.endTime?'–'+esc(e.endTime):''}</strong><br>Europe/Berlin</p><p>${esc(e.place)}${e.address?'<br>'+esc(e.address):''}</p><p>${esc(e.description)}</p>${e.note?`<p class="notice">${esc(e.note)}<br><small>Posted by ${esc(e.updatedBy||'a community member')}</small></p>`:''}<div class="rsvp-panel"><h3>Your attendance</h3><p>${Number(a.going)} going · ${Number(a.maybe)} interested</p><div class="rsvp-options">${[['going','Going'],['maybe','Interested'],['not_going','Can’t make it']].map(([v,l])=>`<button class="btn ${a.mine===v?'primary':'outline'}" data-rsvp="${v}" aria-pressed="${a.mine===v}" ${e.status==='cancelled'?'disabled':''}>${l}</button>`).join('')}</div><p id="rsvpStatus" class="form-status" role="status">${a.mine?'Your response is saved.':'Choose a response to join the plan.'}</p></div><div class="detail-actions"><button class="btn outline" data-calendar="${esc(id)}" ${e.status==='cancelled'||e.status==='postponed'?'disabled':''}>Add to calendar</button><button class="text-link" data-update="${esc(id)}">Post a change</button>${e.category==='food'?'<button class="text-link" data-view="brunch">Open bringing list</button>':''}</div><p class="subtle">Community plans can be updated by anyone with the link. For organizer confirmation, send a private message.</p></div>`;open('eventDetail')}
function openUpdate(id){const e=events.find(e=>e.id===id);if(!e)return;$('eventDetail').close();$('updateForm').reset();$('updateForm').elements.eventId.value=id;$('updateEventTitle').textContent=e.title;status('updateStatus','');open('updateDialog')}
function renderPoll(){const max=Math.max(1,...poll.map(p=>Number(p.vote_count))),total=Number(poll[0]?.total_voters||0);$('pollVoters').textContent=String(total);$('pollChoices').innerHTML=options.map(d=>{const n=Number(poll.find(p=>p.option_date===d)?.vote_count||0);return `<label class="poll-option ${draftVote.includes(d)?'selected':''}"><input type="checkbox" value="${d}" ${draftVote.includes(d)?'checked':''}><span class="poll-option-date">${dateLabel(d,{weekday:'long',day:'numeric',month:'short'})}<small>Evening · time to be confirmed</small><span class="poll-bar"><i style="width:${n/max*100}%"></i></span></span><strong class="poll-result">${n}<small>votes</small></strong></label>`}).join('');const leaders=poll.filter(p=>Number(p.vote_count)===max);$('pollBest').textContent=total?`Most available: ${leaders.map(p=>dateLabel(p.option_date)).join(' · ')}`:'The first vote gets us started.';const dirty=JSON.stringify([...draftVote].sort())!==JSON.stringify([...savedVote].sort());status('pollSaveState',dirty?'You have unsaved changes.':savedVote.length?'Your saved availability is selected.':'Select your dates, then save your availability.')}
function renderBrunchHeading(){const e=events.find(e=>e.id==='brunch-'+session);$('brunchHeading').textContent=dateLabel(e?.date||session,{weekday:'long',day:'numeric',month:'long'});$('brunchNotice').hidden=!e?.note;$('brunchNotice').textContent=e?.note||''}
function renderBrunch(){renderBrunchHeading();$('brunchCount').textContent=brunch.length+' items';$('brunchItems').innerHTML=brunch.length?brunch.map(x=>`<div class="brunch-item"><span class="dish-icon">${icon('brunch')}</span><span class="dish-name"><strong>${esc(x.item)}</strong><small>${esc(x.name||x.display_name||'Community member')}</small></span>${x.mine?`<button class="icon-btn" data-remove-brunch="${esc(x.id)}" aria-label="Remove ${esc(x.item)}">×</button>`:''}</div>`).join(''):'<p class="empty">The table is open. Be the first to bring something.</p>';const all=[...new Set([...suggestions,...posts.filter(p=>p.kind==='brunch-suggestion').map(p=>p.body)])];$('suggestions').innerHTML=all.map(x=>`<div class="suggestion-row"><span>${esc(x)}</span><button class="text-link" data-claim="${esc(x)}">I’ll bring it</button></div>`).join('')}
async function loadBrunch(){const requested=session;try{const rows=await rpc('rb_brunch_session',{p_date:requested,p_device_id:device,p_action:{action:'list'}});if(requested!==session)return;brunch=rows||[];brunchMode='ready';status('brunchStatus','')}catch(e){if(requested!==session)return;if(e.pending){brunchMode='legacy';if(requested==='2026-11-07'){brunch=await db('rb_brunch_items?select=id,item,display_name,created_at&order=created_at.asc&limit=200');status('brunchStatus','November list is shared. Monthly lists and removal are awaiting setup.')}else{brunch=[];status('brunchStatus','This monthly list is awaiting organizer setup.',true)}}else throw e}renderBrunch()}
async function addBrunch(item){if(brunchMode==='ready')await rpc('rb_brunch_session',{p_date:session,p_device_id:device,p_action:{action:'add',item,name:name||'Community member'}});else if(brunchMode==='legacy'&&session==='2026-11-07')await db('rb_brunch_items',{item,display_name:name||'Community member'});else throw Error('This monthly list is awaiting organizer setup. Nothing has been added.');await loadBrunch();toast('Added to the shared table')}
function noteCard(p){const initials=(p.display_name||'Community member').split(/\s+/).slice(0,2).map(n=>n[0]).join('');return `<article class="message-card"><div class="message-card-head"><span class="activity-avatar">${esc(initials)}</span><span><b>${esc(p.display_name||'Community member')}</b><time>${esc(stamp(p.created_at))}</time></span><span class="message-type">${esc(p.kind==='event-update'?'Plan update':p.kind==='event-proposal'?'Proposal':'Group note')}</span></div><p>${esc(p.body)}</p></article>`}
function renderNotes(){const all=[...posts.filter(p=>p.kind!=='brunch-suggestion'),...seedNotes].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));$('messageList').innerHTML=all.map(noteCard).join('');$('homeNotes').innerHTML=all.slice(0,2).map(noteCard).join('')}
async function loadPosts(){posts=await db('rb_community_posts?select=id,kind,display_name,body,metadata,created_at&order=created_at.desc&limit=200')||[];buildEvents();renderNotes();renderBrunch()}
async function post(kind,body,metadata={}){await db('rb_community_posts',{kind,body,metadata,display_name:name||'Community member'});try{await loadPosts()}catch{toast('Saved. The board will refresh when the connection returns.')}}
function chart(rows,goal){
 const sorted=rows.slice().sort((a,b)=>String(a.date).localeCompare(String(b.date)));let running=0;const points=[0,...sorted.map(r=>running+=(r.status==='refunded'?-1:1)*Number(r.amountCents||0))],max=Math.max(goal,...points,100),min=Math.min(0,...points),range=max-min||1;
 const width=Math.max(320,Math.min(680,$('fundChart').clientWidth)),right=width-12;const x=i=>48+i/Math.max(1,points.length-1)*(right-48),y=v=>162-(v-min)/range*134,path=points.map((v,i)=>(i?'L':'M')+x(i).toFixed(1)+','+y(v).toFixed(1)).join(' ');
 $('fundChart').innerHTML=`<svg viewBox="0 0 ${width} 200" role="img" aria-labelledby="chartTitle chartDesc"><title id="chartTitle">Karen’s cumulative confirmed contributions</title><desc id="chartDesc">${rows.length} records. Current net ${money(running)}. Goal ${money(goal)}. Refunds are subtracted.</desc>${[min,(max+min)/2,max].map(v=>`<line x1="48" x2="${right}" y1="${y(v)}" y2="${y(v)}" stroke="#e7ebf1"/><text x="40" y="${y(v)+4}" text-anchor="end" fill="#6b778a" font-size="11">${money(v).replace('€','')}</text>`).join('')}${goal>0?`<line x1="48" x2="${right}" y1="${y(goal)}" y2="${y(goal)}" stroke="#a6b1c3" stroke-dasharray="5 5"/>`:''}<path d="${path} L${right},${y(0)} L48,${y(0)} Z" fill="#fae8ec"/><path d="${path}" fill="none" stroke="#bd2947" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>${points.slice(1).map((v,i)=>`<circle cx="${x(i+1)}" cy="${y(v)}" r="3.5" fill="#bd2947"><title>${esc(dateLabel(sorted[i].date))}: ${money(v)}</title></circle>`).join('')}<text x="48" y="190" fill="#6b778a" font-size="11">${sorted.length?dateLabel(sorted[0].date):'No contributions yet'}</text><text x="${right}" y="190" text-anchor="end" fill="#6b778a" font-size="11">${sorted.length?dateLabel(sorted.at(-1).date):''}</text></svg>`;
}
async function loadFund(){try{
 const data=await rpc('karen_public_state');if(!data?.campaign)throw Error();const c=data.campaign,rows=(data.contributions||[]).filter(r=>['confirmed','received','refunded'].includes(r.status)),net=rows.reduce((s,r)=>s+(r.status==='refunded'?-1:1)*Number(r.amountCents||0),0),goal=Number(c.targetCents||0),pct=goal?Math.max(0,Math.min(100,net/goal*100)):0;
 $('fundTotal').textContent=money(net);$('fundGoal').textContent=money(goal);$('fundPct').textContent=Math.round(pct)+'%';$('fundProgress').style.width=pct+'%';$('fundProgress').parentElement.setAttribute('aria-valuenow',String(Math.round(pct)));$('fundRemaining').textContent=money(Math.max(0,goal-net));$('fundDeadline').textContent=dateLabel(c.endDate,{day:'numeric',month:'short'});$('fundConnection').textContent='Live records';$('fundConnection').classList.add('is-live');$('fundUpdated').textContent='Confirmed records · checked '+new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit'}).format(new Date())+' · refreshes every 30 seconds';$('fundRecordCount').textContent=rows.length+' confirmed records';
 const changed=c.previousTargetCents&&Number(c.previousTargetCents)!==goal;$('targetNotice').hidden=!changed;$('targetNotice').textContent=changed?`Our goal grew from ${money(c.previousTargetCents)} to ${money(goal)}. Every contribution keeps counting.`:'';
 const closed=['draft','closed','archived'].includes(c.status),link=$('fundContribute');if(closed){link.removeAttribute('href');link.setAttribute('aria-disabled','true');link.textContent='Collection closed'}else{const url=c.paymentUrl||cfg.paypalPoolUrl;try{if(new URL(url).protocol==='https:')link.href=url}catch{}link.removeAttribute('aria-disabled');link.textContent='Contribute with PayPal'}
 if(c.showAnalytics!==false)chart(rows,goal);else $('fundChart').innerHTML='<p class="empty">Detailed analytics are not public for this campaign.</p>';
 const te=(data.updates||[]).map(u=>{try{return String(u.title_en||'').startsWith('__EVENT__:')?JSON.parse(u.body_en):null}catch{return null}}).find(e=>e?.slug==='training-functional-garage-0211-karen'&&e.status==='published');if(te){const dt=new Date(te.startsAt),fmt=new Intl.DateTimeFormat('en-CA',{timeZone:te.timeZone||'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit'}),pt=fmt.formatToParts(dt),get=k=>pt.find(p=>p.type===k).value;training={...training,date:`${get('year')}-${get('month')}-${get('day')}`,time:new Intl.DateTimeFormat('en-GB',{timeZone:te.timeZone||'Europe/Berlin',hour:'2-digit',minute:'2-digit'}).format(dt),endTime:te.endsAt?new Intl.DateTimeFormat('en-GB',{timeZone:te.timeZone||'Europe/Berlin',hour:'2-digit',minute:'2-digit'}).format(new Date(te.endsAt)):'',place:te.venueName||training.place,address:te.venueAddress||training.address};$('trainingAddress').textContent=training.address;buildEvents()}
 if(c.showSupporters===false){$('fundSupporters').textContent='Private';$('fundRecent').innerHTML='<p class="empty">Supporter records are private.</p>'}else{try{const supporters=await rpc('solidarity_public_supporters');$('fundSupporters').textContent=String(supporters.length);$('fundRecent').innerHTML=supporters.slice().sort((a,b)=>String(b.lastDate).localeCompare(String(a.lastDate))).slice(0,3).map(s=>`<div class="support-row"><span class="support-avatar">${icon('flag')}</span><span class="support-copy"><b>${esc(s.publicNameConsent&&s.name?s.name:'Supporter '+s.supporterId)}</b><small>${esc(dateLabel(s.lastDate))} · ${Number(s.eventCount||1)} contribution${Number(s.eventCount||1)===1?'':'s'}</small></span><strong>${money(s.netCents)}</strong></div>`).join('')||'<p class="empty">The first contribution will appear here.</p>'}catch{$('fundRecent').innerHTML='<p class="empty">Supporter records are temporarily unavailable.</p>';}}
 }catch{$('fundConnection').textContent='Connection interrupted';$('fundConnection').classList.remove('is-live');$('fundUpdated').textContent='Showing the last loaded records, if available. Retrying automatically.'}}
async function refresh(){if(refreshing||document.hidden)return;refreshing=true;try{const results=await Promise.allSettled([loadFund(),loadPosts(),rpc('rb_powerpoint_results').then(r=>{poll=r||[];renderPoll();renderEvents()}),rpc('rb_event_attendance',{p_device_id:device}).then(r=>{attendance=r||[];renderEvents()}).catch(async e=>{if(e.pending){const n=await rpc('rb_event_interest_count',{p_event_slug:'karting-2026-10-24'});attendance=[{event_id:'karting',going:0,maybe:Number(n||0)}];renderEvents()}else throw e}),loadBrunch()]);setSync(results[1].status==='fulfilled'&&results[2].status==='fulfilled')}finally{refreshing=false}}
function calendar(id){const e=events.find(e=>e.id===id);if(!e?.date)return toast('A date needs to be chosen first.');if(['cancelled','postponed'].includes(e.status))return toast('Wait for a confirmed date before adding this event.');const clean=s=>String(s||'').replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;'),day=e.date.replaceAll('-',''),tim=e.time.replace(':','')+'00';const zone=['BEGIN:VTIMEZONE','TZID:Europe/Berlin','BEGIN:DAYLIGHT','DTSTART:19700329T020000','TZOFFSETFROM:+0100','TZOFFSETTO:+0200','RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU','END:DAYLIGHT','BEGIN:STANDARD','DTSTART:19701025T030000','TZOFFSETFROM:+0200','TZOFFSETTO:+0100','RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU','END:STANDARD','END:VTIMEZONE'];const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Red Banner//Community//EN',...zone,'BEGIN:VEVENT','UID:'+clean(id)+'@red-banner','DTSTAMP:'+new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,''),e.time?`DTSTART;TZID=Europe/Berlin:${day}T${tim}`:`DTSTART;VALUE=DATE:${day}`,...(e.endTime?[`DTEND;TZID=Europe/Berlin:${day}T${e.endTime.replace(':','')}00`]:[]),'SUMMARY:'+clean(e.title+(e.time?'':' (time TBD)')),'LOCATION:'+clean(e.place+(e.address?', '+e.address:'')),'DESCRIPTION:'+clean(e.description+(e.note?'\n'+e.note:'')+'\nCheck the community hub for updates. This calendar copy does not update automatically.'),'END:VEVENT','END:VCALENDAR'];const blob=new Blob([lines.join('\r\n')+'\r\n'],{type:'text/calendar;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='red-banner-'+id+'.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);toast('Calendar event downloaded')}
function contactTabs(){ $('contactTabs').innerHTML='<button type="button" data-conversation="new" class="'+(!activeConversation?'active':'')+'">+ New message</button>'+conversations.map(c=>`<button type="button" data-conversation="${esc(c.id)}" class="${activeConversation?.id===c.id?'active':''}">${esc(c.subject||'Conversation')}</button>`).join('')}
function showConversation(data){$('contactForm').hidden=true;$('contactConversation').hidden=false;$('conversationSubject').textContent=data.thread.subject;$('conversationStatus').textContent=data.thread.status;$('conversationMessages').innerHTML=data.messages.map(m=>`<div class="bubble ${esc(m.sender)}"><b>${m.sender==='organizer'?'Organizer':'You'}</b><p>${esc(m.body)}</p><time>${esc(stamp(m.created_at))}</time></div>`).join('');contactTabs()}
async function loadConversation(c){activeConversation=c;contactTabs();$('contactForm').hidden=true;$('contactConversation').hidden=false;$('conversationSubject').textContent=c.subject||'Conversation';status('replyStatus','Loading…');try{const data=await rpc('rb_contact_member',{p_thread_id:c.id,p_token:c.token,p_action:{action:'read'}});showConversation(data);status('replyStatus','Replies appear here; this conversation refreshes while open.')}catch(e){$('conversationMessages').textContent='Could not load this conversation.';status('replyStatus',e.message,true)}}
function newConversation(){activeConversation=null;pendingConversation=null;$('contactForm').hidden=false;$('contactConversation').hidden=true;$('contactForm').elements.name.value=name;status('contactStatus','');contactTabs()}
function openContact(){ $('moreDialog').close();open('contactDialog');if(activeConversation)loadConversation(activeConversation);else newConversation()}
// Delegated actions also work on cards refreshed from the shared board.
document.addEventListener('click',async e=>{const b=e.target.closest('button,[data-calendar]');if(!b)return;
 if(b.dataset.view){document.querySelectorAll('dialog[open]').forEach(d=>d.close());setView(b.dataset.view)}
 if(b.dataset.close)$(b.dataset.close).close();if(b.hasAttribute('data-contact'))openContact();if(b.hasAttribute('data-propose')){status('eventFormStatus','');open('eventDialog')}
 if(b.dataset.eventOpen)openEvent(b.dataset.eventOpen);if(b.dataset.calendar)calendar(b.dataset.calendar);if(b.dataset.update)openUpdate(b.dataset.update);
 if(b.dataset.rsvp){b.disabled=true;status('rsvpStatus','Saving…');try{await rpc('rb_event_respond',{p_event_id:activeEvent,p_device_id:device,p_response:b.dataset.rsvp});attendance=await rpc('rb_event_attendance',{p_device_id:device});renderEvents();openEvent(activeEvent);toast('Your attendance is saved')}catch(err){status('rsvpStatus',err.pending?'Attendance saving is awaiting organizer setup. Your response has not been saved.':err.message,true)}finally{b.disabled=false}}
 if(b.dataset.claim){setView('brunch');$('brunchItem').value=b.dataset.claim;$('brunchItem').focus()}
 if(b.dataset.removeBrunch){b.disabled=true;try{await rpc('rb_brunch_session',{p_date:session,p_device_id:device,p_action:{action:'remove',id:b.dataset.removeBrunch}});await loadBrunch()}catch(err){status('brunchStatus',err.message,true)}finally{b.disabled=false}}
 if(b.dataset.idea!==undefined){const item=ideas[Number(b.dataset.idea)];$('eventForm').elements.title.value=item[0];$('eventForm').elements.category.value=item[1];$('eventForm').elements.description.value=item[2];open('eventDialog')}
 if(b.dataset.conversation){if(b.dataset.conversation==='new')newConversation();else{const c=conversations.find(x=>x.id===b.dataset.conversation);if(c)loadConversation(c)}}
});
window.addEventListener('hashchange',()=>setView(location.hash.slice(1)));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
$('moreButton').onclick=()=>{open('moreDialog');$('moreButton').setAttribute('aria-expanded','true')};$('moreDialog').addEventListener('close',()=>$('moreButton').setAttribute('aria-expanded','false'));
$('eventSearch').oninput=renderEvents;$('eventFilter').onchange=renderEvents;$('myEvents').onchange=renderEvents;
$('pollChoices').onchange=e=>{const v=e.target.value;draftVote=e.target.checked?[...new Set([...draftVote,v])]:draftVote.filter(d=>d!==v);write('rb-vote-draft',draftVote);renderPoll()};
let pollIdentity=read('rb-poll-identity',{name:name,privacy:'named'}),pollToken=read('rb-poll-token',null),pollClosed=false,pollReady=false;
if(!pollToken){pollToken=[...crypto.getRandomValues(new Uint8Array(32))].map(b=>b.toString(16).padStart(2,'0')).join('');write('rb-poll-token',pollToken)}
$('pollName').value=pollIdentity.name||'';
document.querySelectorAll('[name="pollPrivacy"]').forEach(r=>{r.checked=r.value===pollIdentity.privacy;r.onchange=identityPreview});
function identityPreview(){const privateVote=document.querySelector('[name="pollPrivacy"]:checked')?.value==='private';$('pollIdentityPreview').textContent=privateVote?'A random public ID will be assigned when saved. Your name is disclosed only to organizers after closing.':'The group will see: '+($('pollName').value.trim()||'your name');}
$('pollName').oninput=identityPreview;identityPreview();
async function loadPollPeople(){try{const data=await rpc('rb_poll_public');pollReady=true;pollClosed=data.closed;$('pollLifecycle').textContent=data.closed?'Poll closed · availability is final.':'Poll open · you can update or withdraw your vote.';$('saveVote').disabled=data.closed;$('pollPeople').innerHTML=data.people.length?data.people.map(v=>`<article class="poll-person"><strong>${esc(v.label)}</strong><span>${v.private?'Private name · public ID':'Named participant'}</span><p>${v.dates.map(d=>esc(dateLabel(d))).join(' · ')}</p></article>`).join(''):'<p class="subtle">No named or private-ID votes yet. Earlier votes remain in the totals.</p>';}catch(e){pollReady=false;$('pollLifecycle').textContent='Identity voting is awaiting database activation. No name or vote will be sent until it is ready.';$('pollPeople').textContent='Participant list unavailable.';}}
$('saveVote').onclick=async()=>{const b=$('saveVote'),voterName=$('pollName').value.trim();if(!voterName){$('pollName').focus();status('pollSaveState','Enter a name or recognizable nickname before voting.',true);return}if(!pollReady||pollClosed){status('pollSaveState',pollClosed?'This poll is closed.':'Identity voting is awaiting database activation. Your vote was not sent.',true);return}if(!write('rb-poll-token',pollToken)){status('pollSaveState','Enable browser storage to keep access to your vote.',true);return}b.disabled=true;status('pollSaveState','Saving…');const privacy=document.querySelector('[name="pollPrivacy"]:checked').value;try{const result=await rpc('rb_poll_vote',{p_voter_id:device,p_token:pollToken,p_name:voterName,p_private:privacy==='private',p_dates:draftVote});savedVote=[...draftVote];write('rb-vote-saved',savedVote);pollIdentity={name:voterName,privacy};write('rb-poll-identity',pollIdentity);await loadPollPeople();poll=await rpc('rb_powerpoint_results');renderPoll();renderEvents();status('pollSaveState',draftVote.length?'Saved. '+(privacy==='private'?'Your public ID is '+result.public_id+'.':'Your name is visible to the group.'):'Your availability was withdrawn.');toast('Availability saved')}catch(e){status('pollSaveState','Vote not saved. The poll may have closed or the connection failed. Your draft is kept.',true)}finally{b.disabled=pollClosed}};
loadPollPeople();setInterval(()=>{if(!document.hidden)loadPollPeople()},30000);
$('eventForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f));const ok=await submit(f,'eventFormStatus',async()=>{await post('event-proposal',d.title.trim(),{...d,title:d.title.trim()});status('eventFormStatus','Shared with the group')});if(ok){f.reset();$('eventDialog').close();setView('events');toast('Event proposal shared')}};
$('updateForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f)),ev=events.find(x=>x.id===d.eventId);const ok=await submit(f,'updateStatus',()=>post('event-update',`${ev.title} — ${d.status}: ${d.note.trim()}`,{event_id:d.eventId,status:d.status,date:d.date,time:d.time}));if(ok){f.reset();$('updateDialog').close();toast('Plan update shared')}};
$('messageForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;const ok=await submit(f,'messageStatus',()=>post('note',$('messageInput').value.trim()));if(ok){$('messageInput').value='';status('messageStatus','Posted to the group.')}};
$('brunchSession').onchange=async()=>{session=$('brunchSession').value;brunch=[];buildEvents();renderBrunch();try{await loadBrunch()}catch(e){status('brunchStatus',e.message,true)}};
$('brunchForm').onsubmit=async e=>{e.preventDefault();const ok=await submit(e.currentTarget,'brunchStatus',()=>addBrunch($('brunchItem').value.trim()));if(ok){$('brunchItem').value='';status('brunchStatus','Added to the shared list.')}};
$('suggestionForm').onsubmit=async e=>{e.preventDefault();const ok=await submit(e.currentTarget,'suggestionStatus',()=>post('brunch-suggestion',$('suggestionInput').value.trim()));if(ok){$('suggestionInput').value='';status('suggestionStatus','Suggestion shared.')}};
$('brunchChange').onclick=()=>openUpdate('brunch-'+session);
$('profileButton').onclick=()=>{$('profileForm').elements.name.value=name;open('profileDialog')};$('profileForm').onsubmit=e=>{e.preventDefault();name=e.currentTarget.elements.name.value.trim();write('rb-name',name);$('profileButton').textContent=(name||'R').split(/\s+/).slice(0,2).map(n=>n[0]).join('').toUpperCase();$('profileDialog').close();toast('Display name updated')};
$('shareHub').onclick=async()=>{const url=location.origin+location.pathname;try{if(navigator.share)await navigator.share({title:'The Red Banner Is Raised',url});else{await navigator.clipboard.writeText(url);toast('Hub link copied')}}catch(e){if(e.name!=='AbortError')toast('Copy this address: '+url)}};
$('contactForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f));const ok=await submit(f,'contactStatus',async()=>{if(!pendingConversation){const bytes=crypto.getRandomValues(new Uint8Array(32));pendingConversation={id:crypto.randomUUID(),token:[...bytes].map(b=>b.toString(16).padStart(2,'0')).join(''),subject:d.subject.trim()};conversations.push(pendingConversation);if(!write('rb-private-conversations',conversations)){conversations.pop();pendingConversation=null;throw Error('Enable browser storage before sending so you can receive replies.')}}const c=pendingConversation;const data=await rpc('rb_contact_member',{p_thread_id:c.id,p_token:c.token,p_action:{action:'create',client_id:device,name:d.name.trim(),subject:d.subject.trim(),topic:d.topic,body:d.body.trim()}});activeConversation=c;showConversation(data);pendingConversation=null;status('replyStatus','Delivered to the organizer inbox. Replies will appear here.');f.reset()});if(ok)toast('Private message delivered')};
$('contactReplyForm').onsubmit=async e=>{e.preventDefault();if(!activeConversation)return;await submit(e.currentTarget,'replyStatus',async()=>{const data=await rpc('rb_contact_member',{p_thread_id:activeConversation.id,p_token:activeConversation.token,p_action:{action:'send',body:$('contactReply').value.trim()}});$('contactReply').value='';showConversation(data);status('replyStatus','Reply delivered to the organizer.');})};
$('todayLabel').textContent=new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long'}).format(now);$('profileButton').textContent=(name||'R').split(/\s+/).slice(0,2).map(n=>n[0]).join('').toUpperCase();$('brunchSession').innerHTML=sessions.map(d=>`<option value="${d}">${dateLabel(d,{day:'numeric',month:'long',year:'numeric'})}</option>`).join('');$('ideaGrid').innerHTML=ideas.map(([title,type,description],i)=>`<article class="idea-card tone-${type}"><span class="event-symbol">${icon(types[type].icon)}</span><p class="category-label">${esc(types[type].name)}</p><h2>${esc(title)}</h2><p>${esc(description)}</p><button class="text-link" data-idea="${i}">Make it a plan →</button></article>`).join('');
 buildEvents();renderPoll();renderNotes();renderBrunch();const initialHash=location.hash.slice(1);setView(initialHash);if(initialHash==='contact')openContact();refresh();setInterval(refresh,30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});setInterval(async()=>{if(document.hidden||!$('contactDialog').open||!activeConversation)return;try{const data=await rpc('rb_contact_member',{p_thread_id:activeConversation.id,p_token:activeConversation.token,p_action:{action:'read'}});showConversation(data)}catch{}},15000);
})();
