/* Private inbox: all access is authorized again by the server for each request. */
(()=>{
'use strict';
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
let timer=null;
async function render(host){
 clearInterval(timer);
 const root=node('section',undefined,'admin-panel inbox-workspace'),head=node('div',undefined,'inbox-heading'),intro=node('div');intro.append(node('p','PRIVATE CONVERSATIONS','inbox-eyebrow'),node('h4','Organizer inbox'),node('p','Questions from the collective. Your replies appear in the sender’s private conversation.','admin-hint'));
 const refresh=node('button','Refresh','admin-btn alt');refresh.type='button';head.append(intro,refresh);root.append(head);window.RBPollAdmin?.mount(root,host);
 const status=node('p','Loading conversations…','admin-msg');status.setAttribute('role','status');root.append(status);
 const layout=node('div',undefined,'inbox-layout'),left=node('div',undefined,'inbox-sidebar'),filter=document.createElement('select'),search=document.createElement('input'),list=node('div',undefined,'inbox-list'),detail=node('section',undefined,'inbox-detail');
 search.type='search';search.placeholder='Search name or subject';search.setAttribute('aria-label','Search conversations');filter.setAttribute('aria-label','Filter conversations');[['all','All conversations'],['unread','Unread'],['open','Open'],['answered','Answered'],['resolved','Resolved']].forEach(([v,t])=>{const o=node('option',t);o.value=v;filter.append(o)});
 left.append(search,filter,list);detail.append(node('p','Select a conversation to read and reply.','admin-hint'));layout.append(left,detail);root.append(layout);
 let threads=[],selected=null,busy=false,lastMessageIds='';
 const call=action=>host.rpc('rb_contact_admin',{p_credential:host.getCredential(),p_action:action});
 function fail(){status.textContent='The private inbox is unavailable. It may be awaiting database setup, or your organizer session may have expired. No reply has been sent.';status.classList.add('error')}
 function renderList(){const q=search.value.trim().toLowerCase(),rows=threads.filter(t=>(filter.value==='all'||(filter.value==='unread'?t.admin_unread:t.status===filter.value))&&`${t.display_name} ${t.subject}`.toLowerCase().includes(q));list.replaceChildren();if(!rows.length)list.append(node('p','No matching conversations.','admin-hint'));rows.forEach(t=>{const b=node('button',undefined,'inbox-thread'+(selected===t.id?' active':'')+(t.admin_unread?' unread':''));b.type='button';b.append(node('span',t.display_name||'Community member','inbox-sender'),node('strong',t.subject),node('span',(t.admin_unread?'Unread · ':'')+t.topic+' · '+t.status,'inbox-meta'),node('time',new Date(t.updated_at).toLocaleString('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})));b.onclick=()=>openThread(t.id);list.append(b)})}
 function bubbles(messages,mount){mount.replaceChildren();messages.forEach(m=>{const b=node('article',undefined,'inbox-bubble '+m.sender);b.append(node('b',m.sender==='organizer'?'Organizer':'Member'),node('p',m.body),node('time',new Date(m.created_at).toLocaleString('en-GB')));mount.append(b)});lastMessageIds=messages.map(m=>m.id).join(',')}
 async function openThread(id){if(busy)return;selected=id;renderList();detail.replaceChildren(node('p','Loading conversation…','admin-hint'));try{const data=await call({action:'read',thread_id:id});if(selected!==id)return;const title=node('div',undefined,'inbox-conversation-heading'),meta=node('div');meta.append(node('h3',data.thread.subject),node('p',(data.thread.name||'Community member')+' · '+data.thread.topic+' · '+data.thread.status,'admin-hint'));const resolve=node('button',data.thread.status==='resolved'?'Resolved':'Mark resolved','admin-btn alt');resolve.type='button';resolve.disabled=data.thread.status==='resolved';title.append(meta,resolve);const messages=node('div',undefined,'inbox-messages');messages.setAttribute('aria-live','polite');bubbles(data.messages,messages);const form=document.createElement('form'),label=node('label','Reply privately'),area=document.createElement('textarea'),feedback=node('p','','admin-msg'),send=node('button','Send private reply','admin-btn');area.rows=4;area.maxLength=2000;area.required=true;area.placeholder='Your reply will be visible to this member.';area.id='inboxReply';label.htmlFor=area.id;feedback.setAttribute('role','status');send.type='submit';form.append(label,area,feedback,send);detail.replaceChildren(title,messages,form);
 resolve.onclick=async()=>{resolve.disabled=true;try{await call({action:'resolve',thread_id:id});await load();await openThread(id)}catch{feedback.textContent='Could not resolve this conversation. Please try again.';resolve.disabled=false}};
 form.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;send.disabled=true;feedback.textContent='Sending…';try{const updated=await call({action:'reply',thread_id:id,body:area.value.trim()});bubbles(updated.messages,messages);area.value='';feedback.textContent='Reply delivered. The member can read it in their private conversation.';meta.lastChild.textContent=(updated.thread.name||'Community member')+' · '+updated.thread.topic+' · '+updated.thread.status;resolve.disabled=false;resolve.textContent='Mark resolved';await load()}catch{feedback.textContent='Reply was not sent. Your text is kept here; please try again.'}finally{busy=false;send.disabled=false}};
 const t=threads.find(t=>t.id===id);if(t)t.admin_unread=false;renderList();
 }catch{detail.replaceChildren(node('p','Could not load this conversation. Refresh and try again.','admin-hint'))}}
 async function load(){if(!host.getCredential())return;try{const result=await call({action:'list'});threads=result.threads||[];status.textContent=result.unread+' unread · '+threads.length+' recent conversations';status.classList.remove('error');renderList()}catch{fail()}}
 search.oninput=renderList;filter.onchange=renderList;refresh.onclick=load;
 await load();timer=setInterval(async()=>{if(!root.isConnected){clearInterval(timer);return}if(document.hidden||busy)return;await load();if(selected&&host.getCredential()){try{const data=await call({action:'read',thread_id:selected});const ids=data.messages.map(m=>m.id).join(',');const mount=detail.querySelector('.inbox-messages');if(mount&&ids!==lastMessageIds)bubbles(data.messages,mount)}catch{}}},15000);
 return root;
}
async function refreshBadge(host){if(!host?.getCredential())return;try{const result=await host.rpc('rb_contact_admin',{p_credential:host.getCredential(),p_action:{action:'list'}});window.RBAdminInbox.unreadCount=Number(result.unread||0);document.querySelectorAll('[data-admin-tab="inbox"]').forEach(b=>b.textContent='Inbox'+(result.unread?' ('+result.unread+')':''))}catch{}}
window.RBAdminInbox={render,refreshBadge,unreadCount:0};
})();
