/* Device-local update inbox. No phone numbers, server push subscriptions or remote sends. */
(()=>{'use strict';
const $=s=>document.querySelector(s),t=s=>window.RBLocale?.t(s)||s;
const get=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
let storageOK=true;const put=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true}catch{storageOK=false;return false}};
let prefs={official:true,replies:true,browser:false,...get('rb-alert-prefs',{})},follows=get('rb-event-follows',{}),entries=get('rb-alerts',[]),seen=get('rb-alert-seen',{}),busy=false;
const dialog=document.createElement('dialog');dialog.id='notificationsDialog';dialog.className='notifications-dialog';dialog.setAttribute('aria-labelledby','notificationsTitle');
dialog.innerHTML=`<header class="notifications-head"><div><p class="eyebrow">STAY IN THE COLLECTIVE</p><h2 id="notificationsTitle">The signal box.</h2><p>Updates, replies and the plans you follow.</p></div><button class="icon-btn" data-alert-close aria-label="Close notifications">×</button></header><div class="notifications-body"><section class="alert-inbox"><div class="alert-toolbar"><h3>On this device</h3><button class="text-link" data-alert-read>Mark all read</button></div><p class="alert-connection" id="alertConnection" role="status">Checking for updates…</p><div id="alertList"></div><section class="followed-plans"><h3>Your followed plans</h3><p>Follow an event from its details to track changes here.</p><div id="followedPlans"></div></section></section><aside class="alert-settings"><p class="eyebrow">YOUR ATTENTION, YOUR RULES</p><h3>Choose your signals.</h3><label><input type="checkbox" data-alert-pref="official"><span><b>Official announcements</b><small>Updates published by organizers.</small></span></label><label><input type="checkbox" data-alert-pref="replies"><span><b>Private organizer replies</b><small>Alerts never include the message text.</small></span></label><div class="delivery-card"><span class="delivery-status">Available while open</span><h4>Browser alerts</h4><p>Checks run while this app is open and visible. No alerts are sent after you close it.</p><button class="btn outline" data-browser-alerts>Enable browser alerts</button><p id="browserAlertStatus" class="form-status" role="status"></p></div><div class="delivery-card external-delivery"><span class="delivery-status pending">Not connected</span><h4>WhatsApp · SMS · Signal</h4><p>Automatic phone delivery needs a connected sender service. No phone number is collected here yet.</p><p>You can already share any event through WhatsApp or your phone’s share menu.</p></div><button class="text-link" data-alert-clear>Clear local notification history</button><p class="alert-local-note">Preferences and history stay in this browser. They do not sync between devices.</p></aside></div>`;
document.body.append(dialog);
const element=(tag,text,cls)=>{const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n};
function status(message){$('#alertConnection').textContent=t(message)}
function render(){
 const unread=entries.filter(n=>!n.read).length,badge=$('#notificationCount');if(badge){badge.hidden=!unread;badge.textContent=unread>9?'9+':String(unread)}
 const list=$('#alertList');list.replaceChildren();
 if(!entries.length)list.append(element('p',t('All quiet for now. New updates will appear here.'),'alert-empty'));
 entries.forEach(n=>{const card=element('article','',`alert-item ${n.read?'':'unread'}`),label=element('span',t(n.kind),'alert-kind'),title=element('h4',n.title),body=element('p',n.body),date=element('time',new Intl.DateTimeFormat(window.RBLocale?.locale||'en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(n.at))),btn=element('button',t('Open update'),'text-link');title.setAttribute('translate','no');body.setAttribute('translate','no');btn.onclick=()=>{n.read=true;put('rb-alerts',entries);dialog.close();render();if(n.eventId)window.RBCommunity?.openEvent(n.eventId);else if(n.kind==='Private reply')window.RBCommunity?.openConversation(n.threadId);else document.querySelector('[data-view=messages]')?.click()};card.append(label,date,title,body,btn);list.append(card)});
 const plans=$('#followedPlans');plans.replaceChildren();Object.entries(follows).forEach(([id,f])=>{const row=element('div','','follow-row'),button=element('button',f.title,'text-link'),unfollow=element('button',t('Unfollow'),'text-link');button.setAttribute('translate','no');button.onclick=()=>{dialog.close();window.RBCommunity?.openEvent(id)};unfollow.onclick=()=>{delete follows[id];put('rb-event-follows',follows);render()};row.append(button,unfollow);plans.append(row)});
 dialog.querySelectorAll('[data-alert-pref]').forEach(c=>c.checked=Boolean(prefs[c.dataset.alertPref]));$('#browserAlertStatus').textContent=t(prefs.browser?'Enabled while this app is open.':'Off. You control browser permission.');dialog.querySelector('[data-browser-alerts]').textContent=t(prefs.browser?'Turn off browser alerts':'Enable browser alerts');
 if(!storageOK)status('Browser storage is unavailable. Changes will last only for this visit.');
}
async function browserAlert(){if(!prefs.browser||!('Notification'in window)||Notification.permission!=='granted')return;try{const reg=await navigator.serviceWorker?.getRegistration();if(reg)await reg.showNotification(t('The Red Banner Is Raised'),{body:t('There is a new update in your signal box.'),tag:'red-banner-updates',icon:'./assets/banner-touch.png',data:{url:new URL('./#notifications',location.href).href}});else new Notification(t('The Red Banner Is Raised'),{body:t('There is a new update in your signal box.'),tag:'red-banner-updates'})}catch{/* In-app notification remains available. */}}
function add(n,notify=true){if(entries.some(x=>x.id===n.id))return;entries=[{...n,at:n.at||new Date().toISOString(),read:!notify},...entries].slice(0,80);put('rb-alerts',entries);render();if(notify)browserAlert()}
function signature(e){return JSON.stringify([e.date,e.time,e.place,e.status,e.note||''])}
function watchEvents(events){for(const e of events){const f=follows[e.id];if(!f)continue;const signatureNow=signature(e);if(f.signature!==signatureNow){add({id:'event:'+e.id+':'+signatureNow,kind:'Community event update',title:e.title,body:[e.date,e.time||t('Time TBD'),t(({cancelled:'Cancelled',postponed:'Postponed',scheduled:'On the calendar',changed:'Updated',proposed:'Proposed'})[e.status]||'Updated'),e.note||''].filter(Boolean).join(' · '),eventId:e.id});f.signature=signatureNow;f.title=e.title;put('rb-event-follows',follows)}}}
async function readAPI(path,body){const c=window.KAREN_SUPABASE;if(!c?.url)throw Error('Unavailable');const r=await fetch(c.url+'/rest/v1/'+path,{method:body?'POST':'GET',headers:{apikey:c.key,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('Unavailable');return r.json()}
async function check(){if(busy||document.hidden)return;busy=true;let failed=false;try{
 if(prefs.official){try{const rows=await readAPI('rb_official_notices?select=id,title,body,updated_at&order=updated_at.desc&limit=20');const initial=!seen.official;for(const r of [...rows].reverse()){const key=r.id+':'+r.updated_at;if(seen['notice:'+r.id]!==key){add({id:'notice:'+key,kind:'Official announcement',title:r.title,body:r.body,at:r.updated_at},!initial);seen['notice:'+r.id]=key}}seen.official=true}catch{failed=true}}
 if(prefs.replies){const conversations=get('rb-private-conversations',[]).slice(-20);for(const c of conversations){try{const data=await readAPI('rpc/rb_contact_member',{p_thread_id:c.id,p_token:c.token,p_action:{action:'read'}});const messages=data.messages.filter(m=>m.sender==='organizer');const last=messages.at(-1);if(last){const key=last.id||last.created_at;if(seen['reply:'+c.id]!==key){add({id:'reply:'+c.id+':'+key,kind:'Private reply',threadId:c.id,title:t('An organizer replied.'),body:t('Open your private conversation to read the message.'),at:last.created_at});seen['reply:'+c.id]=key}}}catch{failed=true}}}
 put('rb-alert-seen',seen);status(failed?'Some updates could not be checked. We will retry.':'Up to date · checks every 30 seconds while open.');
 }finally{busy=false}}
function show(){document.querySelector('#moreDialog')?.close();render();if(!dialog.open)dialog.showModal();check()}
document.addEventListener('click',e=>{if(e.target.closest('[data-notifications]'))show()});dialog.querySelector('[data-alert-close]').onclick=()=>dialog.close();dialog.querySelector('[data-alert-read]').onclick=()=>{entries.forEach(n=>n.read=true);put('rb-alerts',entries);render()};dialog.querySelector('[data-alert-clear]').onclick=()=>{entries=[];put('rb-alerts',entries);render()};
dialog.querySelectorAll('[data-alert-pref]').forEach(c=>c.onchange=()=>{prefs[c.dataset.alertPref]=c.checked;put('rb-alert-prefs',prefs);check()});
dialog.querySelector('[data-browser-alerts]').onclick=async()=>{if(prefs.browser){prefs.browser=false;put('rb-alert-prefs',prefs);render();return}if(!('Notification'in window)){return $('#browserAlertStatus').textContent=t('Browser alerts are unavailable here. On iPhone, add this app to your Home Screen and open it there.')}try{const permission=await Notification.requestPermission();prefs.browser=permission==='granted';put('rb-alert-prefs',prefs);render();if(!prefs.browser)$('#browserAlertStatus').textContent=t('Permission was not granted. You can change this in browser settings.')}catch{$('#browserAlertStatus').textContent=t('Browser alerts could not be enabled. The in-app inbox still works.')}};
window.RBNotifications={attach(root,event){const box=element('section','','event-notifications'),head=element('h3',t('Keep this plan close.')),follow=element('button',t(follows[event.id]?'Following this event':'Follow event updates'),'btn outline');follow.setAttribute('aria-pressed',Boolean(follows[event.id]));follow.onclick=()=>{if(follows[event.id])delete follows[event.id];else follows[event.id]={title:event.title,signature:signature(event)};put('rb-event-follows',follows);follow.textContent=t(follows[event.id]?'Following this event':'Follow event updates');follow.setAttribute('aria-pressed',Boolean(follows[event.id]));render()};const note=element('p',t('Changes appear in your signal box when you open this app. Calendar reminders work separately.'),'subtle');const actions=element('div','','event-share-actions');
 const url=new URL('./',location.href);url.hash='events';url.searchParams.set('event',event.id);const text=[event.title,event.date,event.time||t('Time TBD'),event.place,url.href].join('\n');
 const whatsapp=element('a','WhatsApp','btn outline');whatsapp.href='https://wa.me/?text='+encodeURIComponent(text);whatsapp.target='_blank';whatsapp.rel='noopener noreferrer';
 const share=element('button',t('Signal / other apps'),'btn outline'),result=element('p','','form-status');result.setAttribute('role','status');share.onclick=async()=>{try{if(navigator.share){await navigator.share({title:event.title,text:[event.date,event.time||t('Time TBD'),event.place].join(' · '),url:url.href})}else{await navigator.clipboard.writeText(text);result.textContent=t('Copied. Paste into Signal or another app.')}}catch(e){if(e.name!=='AbortError')result.textContent=t('Sharing is unavailable. Copy the event link below.')}};
 const copy=element('button',t('Copy link'),'text-link');copy.onclick=async()=>{try{await navigator.clipboard.writeText(url.href);result.textContent=t('Event link copied.')}catch{result.textContent=url.href}};actions.append(whatsapp,share,copy);box.append(head,follow,note,actions,result);root.append(box)}};
window.addEventListener('rb-events-loaded',e=>watchEvents(e.detail));window.addEventListener('rb-language-change',render);window.addEventListener('rb-language-ready',render);document.addEventListener('visibilitychange',()=>{if(!document.hidden)check()});window.addEventListener('hashchange',()=>{if(location.hash==='#notifications')show()});render();check();setInterval(check,30000);if(location.hash==='#notifications'||window.RBCommunity?.initialHash==='notifications')show();
const linkedEvent=new URLSearchParams(location.search).get('event');if(linkedEvent&&document.querySelector('#eventDetail')?.open)window.RBCommunity?.openEvent(linkedEvent);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
