window.RBApp=(()=>{
const C=window.KAREN_SUPABASE,L=window.SOLIDARITY_LOCALES,$=id=>document.getElementById(id),RTL=new Set(L.rtl||[]);
let lang=localStorage.getItem("solidarity_lang")||"en",fund=null,shuffleNonce=Number(sessionStorage.getItem("supporter_shuffle")||Date.now());
const t=k=>L.ui?.[lang]?.[k]||L.ui?.en?.[k]||k;
function euro(n){try{return new Intl.NumberFormat(lang,{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(Number(n||0))}catch{return "€"+Math.round(Number(n||0))}}
function dateFmt(v,short=false){if(!v)return"—";const d=new Date(String(v).slice(0,10)+"T12:00:00");try{return new Intl.DateTimeFormat(lang,{day:"numeric",month:"short",...(short?{}:{year:"numeric"})}).format(d)}catch{return String(v)}}
async function rpc(name,body={}){const r=await fetch(C.url+"/rest/v1/rpc/"+name,{method:"POST",headers:{"Content-Type":"application/json",apikey:C.key},body:JSON.stringify(body)}),x=await r.text();if(!r.ok)throw Error(x||"request_failed");return x?JSON.parse(x):null}
function localeContent(c){const all=c?.localeContent||{};return all[lang]||all.en||{}}
function compute(d){const rows=(d.contributions||[]).filter(x=>["confirmed","received","refunded"].includes(x.status)),pos=rows.filter(x=>x.status!=="refunded"),gross=pos.reduce((s,x)=>s+Number(x.amountCents||0),0),refunds=rows.filter(x=>x.status==="refunded").reduce((s,x)=>s+Number(x.amountCents||0),0),net=Math.max(0,gross-refunds),spent=(d.expenses||[]).filter(x=>x.status==="recorded").reduce((s,x)=>s+Number(x.amountCents||0),0),available=Math.max(0,net-spent),target=Number(d.campaign?.targetCents||0);return{rows,pos,gross,refunds,net,spent,available,target,pct:target?Math.min(100,net/target*100):0}}
function status(s){const M={fr:{active:"EN DIRECT",goal_reached:"OBJECTIF ATTEINT",closed:"CLÔTURÉE",archived:"ARCHIVÉE",draft:"BROUILLON"},de:{active:"LIVE",goal_reached:"ZIEL ERREICHT",closed:"BEENDET",archived:"ARCHIVIERT",draft:"ENTWURF"},es:{active:"EN VIVO",goal_reached:"OBJETIVO ALCANZADO",closed:"CERRADA",archived:"ARCHIVADA",draft:"BORRADOR"},it:{active:"LIVE",goal_reached:"OBIETTIVO RAGGIUNTO",closed:"CHIUSA",archived:"ARCHIVIATA",draft:"BOZZA"},pt:{active:"AO VIVO",goal_reached:"META ALCANÇADA",closed:"ENCERRADA",archived:"ARQUIVADA",draft:"RASCUNHO"},nl:{active:"LIVE",goal_reached:"DOEL BEREIKT",closed:"GESLOTEN",archived:"GEARCHIVEERD",draft:"CONCEPT"},ar:{active:"مباشر",goal_reached:"تم بلوغ الهدف",closed:"مغلق",archived:"مؤرشف",draft:"مسودة"}};return M[lang]?.[s]||({active:"LIVE",goal_reached:"GOAL REACHED",closed:"CLOSED",archived:"ARCHIVED",draft:"DRAFT"}[s]||"LIVE")}
function seed(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
const shuffled=(a,b)=>seed(String(a.id)+":"+shuffleNonce)-seed(String(b.id)+":"+shuffleNonce);
function fillLanguages(c){const sel=$("languageSelect"),enabled=c?.enabledLocales?.length?c.enabledLocales:["en","fr"];if(!enabled.includes(lang))lang=enabled.includes("en")?"en":enabled[0];sel.replaceChildren();enabled.forEach(code=>{const o=document.createElement("option");o.value=code;o.textContent=L.names[code]||code.toUpperCase();o.selected=code===lang;sel.append(o)})}
function applyLanguage(){document.documentElement.lang=lang;document.documentElement.dir=RTL.has(lang)?"rtl":"ltr";document.querySelectorAll("[data-i18n]").forEach(el=>el.textContent=t(el.dataset.i18n))}
function setLanguage(x){lang=x;localStorage.setItem("solidarity_lang",lang);applyLanguage();if(fund)render(fund)}
function render(d){fund=d;const c=d.campaign||{},m=compute(d),lc=localeContent(c);fillLanguages(c);applyLanguage();document.title=(lc.title||c.title||"Solidarity Fund")+" · Live";$("brandCampaign").textContent=lc.title||c.title||"Solidarity Fund";const P={fr:"POUR ",de:"FÜR ",es:"PARA ",it:"PER ",pt:"PARA ",nl:"VOOR ",ar:"من أجل "};$("campaignKicker").textContent=c.beneficiary?(P[lang]||"FOR ")+c.beneficiary:"SOLIDARITY";$("campaignTitle").textContent=lc.subtitle||c.subtitle||lc.title||c.title||"We carry it together.";$("campaignStory").textContent=lc.story||c.story_en||"";$("campaignStatus").textContent=status(c.status);$("lastUpdated").textContent=dateFmt(d.updated);
$("raisedTotal").textContent=euro(m.net/100);$("goalText").textContent=(lang==="fr"?"sur ":lang==="de"?"von ":lang==="ar"?"من ":"of ")+euro(m.target/100);$("progressPct").textContent=Math.round(m.pct)+"%";$("supporterCount").textContent=m.pos.length;$("remainingAmount").textContent=euro(Math.max(0,m.target-m.net)/100);$("progressLine").style.width=m.pct+"%";
const url=c.paymentUrl||C.paypalPoolUrl||"https://www.paypal.com/pool/9tfV5v7iJ3",label=lc.paymentLabel||c.paymentLabel_en||t("payWithPayPal"),closed=["draft","closed","archived"].includes(c.status);["topPayBtn","heroPayBtn","mobilePayBtn"].forEach(id=>{const a=$(id);if(!a)return;a.href=url;a.classList.toggle("hidden",closed)});$("paymentLabel").textContent=label;
const vals=m.pos.map(x=>Number(x.amountCents||0)).sort((a,b)=>a-b),mean=vals.length?m.gross/vals.length:0,median=vals.length?(vals.length%2?vals[Math.floor(vals.length/2)]:(vals[vals.length/2-1]+vals[vals.length/2])/2):0,min=vals[0]||0,max=vals.at(-1)||0,gap=Math.max(0,m.target-m.net),needed=median?Math.ceil(gap/median):0;$("statNet").textContent=euro(m.net/100);$("statMean").textContent=euro(mean/100);$("statMedian").textContent=euro(median/100);$("statRange").textContent=euro(min/100)+"–"+euro(max/100);$("statGap").textContent=euro(gap/100);$("statNeeded").textContent=needed||"—";
const showAnalytics=c.showAnalytics!==false;$("observatory").classList.toggle("hidden",!showAnalytics);if(showAnalytics)window.RedBannerCharts?.render(d,m,{t,euro,dateFmt});window.RBSections?.render(d,m,{lang,t,euro,dateFmt,localeContent,shuffled});$("footerCampaign").textContent=(lc.title||c.title||"Solidarity Fund")+" · "+status(c.status)}
async function refresh(){try{render(await rpc("karen_public_state"))}catch{$("campaignStory").textContent=t("noData")}}
function reshuffle(){shuffleNonce=Date.now()+Math.floor(Math.random()*1e5);sessionStorage.setItem("supporter_shuffle",String(shuffleNonce));if(fund)window.RBSections?.supporters(fund,compute(fund),{lang,t,euro,dateFmt,shuffled})}
async function share(){const c=fund?.campaign||{},lc=localeContent(c),m=fund?compute(fund):null,data={title:lc.title||c.title||"Solidarity Fund",text:(lc.subtitle||c.subtitle||"")+" "+(m?euro(m.net/100):""),url:location.href};try{if(navigator.share)await navigator.share(data);else await navigator.clipboard.writeText(location.href)}catch{}}
function start(){$("languageSelect").onchange=e=>setLanguage(e.target.value);$("reshuffleBtn").onclick=reshuffle;$("shareBtn").onclick=share;if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));refresh().then(()=>window.RBConsent?.init()) ;setInterval(refresh,30000)}
return{start,refresh,rpc,t,euro,dateFmt,get lang(){return lang},compute,get fund(){return fund}};
})();