const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright-core');
const assert=require('node:assert/strict');
(async()=>{const http=require('node:http'),fs=require('node:fs'),path=require('node:path');const server=http.createServer((q,r)=>{const f=path.join(__dirname,'..',q.url.split('?')[0].split('#')[0]==='/'?'index.html':q.url.split('?')[0]);try{r.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':f.endsWith('.json')?'application/json':f.endsWith('.svg')?'image/svg+xml':'text/html');r.end(fs.readFileSync(f))}catch{r.statusCode=404;r.end()}});await new Promise(resolve=>server.listen(8881,'127.0.0.1',resolve));const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'});const page=await context.newPage();page.on('pageerror',e=>console.log('PAGE ERROR',e.message));let state={push:false,sms:false,whatsapp:false,preferences:{quietStart:22,quietEnd:8}},calls=[];
await page.addInitScript(()=>{window.Notification={permission:'granted',requestPermission:async()=>'granted'};window.PushManager=function(){};let sub=null;const reg={pushManager:{getSubscription:async()=>sub,subscribe:async()=>sub={toJSON:()=>({endpoint:'https://fcm.googleapis.com/mock',keys:{auth:'a'.repeat(22),p256dh:'a'.repeat(87)}}),unsubscribe:async()=>{sub=null;return true}}}};Object.defineProperty(navigator,'serviceWorker',{value:{register:async()=>reg,ready:Promise.resolve(reg),getRegistration:async()=>reg}})});
await page.route('**/rest/v1/**',r=>r.fulfill({json:r.request().url().includes('rb_contact_member')?{messages:[]}:[]}));
await page.route('**/functions/v1/red-banner-notifications',async r=>{if(r.request().method()==='GET')return r.fulfill({json:{push:true,sms:false,whatsapp:false,publicKey:'a'.repeat(87)}});const b=r.request().postDataJSON();calls.push(b.action);if(b.action==='register')state={...state,push:!!b.subscription,preferences:b.preferences};if(b.action==='preferences')state.preferences=b.preferences;if(b.action==='unsubscribe')state.push=false;return r.fulfill({json:b.action==='status'?state:{saved:true}})});
await page.goto('http://127.0.0.1:8881/');await page.waitForFunction(()=>window.RBCalendar&&document.querySelector('.language-switch select'));await page.screenshot({path:'/tmp/rb-qa/home-mobile.png'});
await page.locator('[data-event-open="karen-training"]').first().click();await page.getByRole('button',{name:'Save to my agenda',exact:true}).click();await page.locator('#eventDetail [data-calendar]').click();await page.locator('#calendarDialog').waitFor({state:'visible'});assert.equal(new URL(await page.locator('#calendarDialog a').first().getAttribute('href')).searchParams.get('dates'),'20261017T093000Z/20261017T113000Z');await page.screenshot({path:'/tmp/rb-qa/calendar-mobile.png'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const download=page.waitForEvent('download');await page.getByRole('button',{name:'Apple Calendar'}).click();assert((await download).suggestedFilename().endsWith('.ics'));await page.locator('[data-close-calendar]').click();await page.evaluate(()=>document.querySelector('#eventDetail').close());assert(await page.locator('.saved-plan').count()===1);
for(const lang of ['fr','de']){await page.locator('.language-switch select').selectOption(lang);await page.evaluate(()=>scrollTo(0,0));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/rb-qa/home-'+lang+'.png'});}await page.locator('.language-switch select').selectOption('en');await page.setViewportSize({width:1440,height:1050});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'/tmp/rb-qa/home-desktop.png'});for(const width of [320,390]){await page.setViewportSize({width,height:844});for(const theme of ['light','dark','contrast']){await page.evaluate(theme=>document.documentElement.dataset.theme=theme,theme);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}}console.log('PASS: calendar chooser, Google UTC, Apple download, save agenda, EN/FR/DE mobile width');await browser.close();server.close()})().catch(e=>{console.error(e);process.exit(1)});
