import webpush from 'npm:web-push@3.6.7';
import {SITE,subscriptionOK,preferences,quiet,message} from './core.mjs';
const URLBASE=Deno.env.get('SUPABASE_URL')!,SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const env=(n:string)=>Deno.env.get(n)||'';
const headers={'apikey':SERVICE,'Authorization':'Bearer '+SERVICE,'Content-Type':'application/json'};
const cors={'Access-Control-Allow-Origin':SITE,'Access-Control-Allow-Headers':'content-type','Access-Control-Allow-Methods':'POST, GET, OPTIONS','Vary':'Origin'};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{...cors,'Content-Type':'application/json','Cache-Control':'no-store'}});
class Failure extends Error{constructor(public status:number,message:string){super(message)}}
async function db(path:string,method='GET',body?:unknown){const r=await fetch(URLBASE+'/rest/v1/'+path,{method,headers:{...headers,Prefer:'return=representation'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Failure(503,'Notification storage is unavailable.');return r.status===204?null:r.json()}
async function hash(s:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(x=>x.toString(16).padStart(2,'0')).join('')}
const uuid=(s:unknown)=>typeof s==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(s);
async function config(){let rows=await db('rb_push_config?select=*');if(!rows.length){const vapid=webpush.generateVAPIDKeys();const worker_token=crypto.randomUUID()+crypto.randomUUID();await fetch(URLBASE+'/rest/v1/rb_push_config?on_conflict=id',{method:'POST',headers:{...headers,Prefer:'resolution=ignore-duplicates'},body:JSON.stringify({id:true,vapid,worker_token})});rows=await db('rb_push_config?select=*')}if(!rows.length)throw new Failure(503,'Push configuration unavailable.');return rows[0]}
const phoneReady=()=>Boolean(env('TWILIO_ACCOUNT_SID')&&env('TWILIO_AUTH_TOKEN')&&env('TWILIO_VERIFY_SERVICE_SID')&&env('TURNSTILE_SECRET_KEY')&&env('TURNSTILE_SITE_KEY')&&env('TWILIO_WEBHOOK_URL')&&env('TWILIO_OPT_OUT_CONFIGURED')==='true');
function channels(){return {sms:phoneReady()&&Boolean(env('TWILIO_MESSAGING_SERVICE_SID')),whatsapp:phoneReady()&&Boolean(env('TWILIO_WHATSAPP_FROM')&&env('TWILIO_WHATSAPP_CONTENT_SID'))}}
async function limit(key:string,max:number){if(!await db('rpc/rb_push_limit','POST',{p_key:key,p_max:max}))throw new Failure(429,'Too many attempts. Please try later.')}
async function device(b:any){if(!uuid(b.id)||!/^\w{64}$/.test(b.token||''))throw new Failure(401,'Device credentials are missing.');const rows=await db('rb_push_devices?id=eq.'+b.id+'&select=*');const row=rows[0];if(!row||row.token_hash!==await hash(b.token))throw new Failure(401,'Device access was not verified.');return row}
async function twilio(path:string,body:Record<string,string>,verify=false){const r=await fetch((verify?'https://verify.twilio.com/v2/Services/'+env('TWILIO_VERIFY_SERVICE_SID')+'/':'https://api.twilio.com/2010-04-01/Accounts/'+env('TWILIO_ACCOUNT_SID')+'/')+path,{method:'POST',headers:{Authorization:'Basic '+btoa(env('TWILIO_ACCOUNT_SID')+':'+env('TWILIO_AUTH_TOKEN')),'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(body),signal:AbortSignal.timeout(15000)});const data=await r.json();if(!r.ok)throw new Failure(502,'Messaging provider rejected the request.');return data}
async function dispatch(c:any){const jobs=await db('rpc/rb_push_claim','POST',{});let accepted=0;await Promise.all(jobs.map(async(j:any)=>{const rows=await db('rb_push_devices?id=eq.'+j.device_id+'&select=*'),d=rows[0];if(!d)return;const p=preferences(d.preferences);if((j.kind==='official'&&!p.official)||(j.kind==='reply'&&!p.replies)||(j.kind==='event'&&!p.events.includes(j.event_id))){await db('rb_push_jobs?id=eq.'+j.id,'PATCH',{status:'cancelled'});return}if(quiet(p)&&j.kind!=='test'){await db('rb_push_jobs?id=eq.'+j.id,'PATCH',{status:'pending',attempts:Math.max(0,j.attempts-1),available_at:new Date(Date.now()+15*60000).toISOString()});return}try{const body=message(j.kind,p.language);if(j.channel==='push'){if(!d.subscription||!subscriptionOK(d.subscription))throw new Failure(410,'Unsubscribed');await webpush.sendNotification(d.subscription,JSON.stringify({title:'The Red Banner Is Raised',body,url:SITE+'/#notifications',tag:j.event_key}),{vapidDetails:{subject:SITE,publicKey:c.vapid.publicKey,privateKey:c.vapid.privateKey},TTL:3600,timeout:12000});}else if(j.channel==='sms'){if(!channels().sms||!d.sms||!d.phone)throw new Failure(410,'Channel unavailable');await twilio('Messages.json',{To:d.phone,MessagingServiceSid:env('TWILIO_MESSAGING_SERVICE_SID'),Body:'Red Banner: '+body+' '+SITE+'/#notifications\nReply STOP to unsubscribe.'});}else{if(!channels().whatsapp||!d.whatsapp||!d.phone)throw new Failure(410,'Channel unavailable');await twilio('Messages.json',{To:'whatsapp:'+d.phone,From:env('TWILIO_WHATSAPP_FROM'),ContentSid:env('TWILIO_WHATSAPP_CONTENT_SID'),ContentVariables:JSON.stringify({'1':body,'2':SITE+'/#notifications'})})}await db('rb_push_jobs?id=eq.'+j.id,'PATCH',{status:'accepted',last_error:null});accepted++}catch(e:any){const gone=[404,410].includes(e.statusCode||e.status);if(gone&&j.channel==='push')await db('rb_push_devices?id=eq.'+d.id,'PATCH',{subscription:null});await db('rb_push_jobs?id=eq.'+j.id,'PATCH',{status:gone||j.attempts>=4?'failed':'pending',last_error:gone?'Subscription unavailable':'Provider did not accept request',available_at:new Date(Date.now()+j.attempts*5*60000).toISOString()})}}));
return {processed:jobs.length,accepted}}
async function webhook(req:Request){const form=await req.formData();const fields=Array.from(form.entries()).map(([k,v])=>[k,String(v)]).sort(([a],[b])=>a<b?-1:a>b?1:0);const canonical=env('TWILIO_WEBHOOK_URL')+fields.map(([k,v])=>k+v).join('');const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(env('TWILIO_AUTH_TOKEN')),{name:'HMAC',hash:'SHA-1'},false,['sign']);const sig=btoa(String.fromCharCode(...new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(canonical)))));if(!env('TWILIO_WEBHOOK_URL')||await hash(sig)!==await hash(req.headers.get('x-twilio-signature')||''))throw new Failure(401,'Unauthorized');const from=String(form.get('From')||'').replace(/^whatsapp:/,'');const stop=String(form.get('OptOutType')||'').toUpperCase()==='STOP'||['STOP','STOPALL','UNSUBSCRIBE','CANCEL','END','QUIT'].includes(String(form.get('Body')||'').trim().toUpperCase());if(stop&&/^\+[1-9][0-9]{7,14}$/.test(from))await db('rb_push_devices?phone=eq.'+encodeURIComponent(from),'PATCH',{sms:false,whatsapp:false});return new Response('<Response/>',{headers:{'Content-Type':'text/xml'}})}
Deno.serve(async req=>{try{
if(new URL(req.url).searchParams.get('twilio')==='1'&&req.method==='POST')return await webhook(req);
if(req.method==='OPTIONS')return new Response(null,{headers:cors});
const c=await config();
if(req.headers.has('x-worker-token')){if(await hash(req.headers.get('x-worker-token')||'')!==await hash(c.worker_token))throw new Failure(401,'Unauthorized');return json(await dispatch(c))}
const origin=req.headers.get('origin');if(origin&&origin!==SITE)throw new Failure(403,'Origin not allowed');
if(req.method==='GET')return json({push:true,publicKey:c.vapid.publicKey,...channels(),turnstileSiteKey:env('TURNSTILE_SITE_KEY')});
if(req.method!=='POST')throw new Failure(405,'Method not allowed');
const raw=await req.text();if(raw.length>20000)throw new Failure(413,'Request too large');const b=JSON.parse(raw);
if(b.action==='register'){
 if(!uuid(b.id)||!/^[a-f0-9]{64}$/.test(b.token||''))throw new Failure(400,'Invalid device credentials');
 const rows=await db('rb_push_devices?id=eq.'+b.id+'&select=id');if(rows.length)await device(b);else{await limit('registrations',500);if((await db('rb_push_devices?select=id&limit=5001')).length>=5000)throw new Failure(429,'Registration limit reached');}
 if(b.subscription!==null&&!subscriptionOK(b.subscription))throw new Failure(400,'Unsupported push subscription');
 const row={id:b.id,token_hash:await hash(b.token),subscription:b.subscription,preferences:preferences(b.preferences),updated_at:new Date().toISOString()};
 if(rows.length)await db('rb_push_devices?id=eq.'+b.id,'PATCH',row);else await db('rb_push_devices','POST',row);
 return json({saved:true});
}
const d=await device(b);await limit('device:'+d.id,120);
if(b.action==='status')return json({push:Boolean(d.subscription),sms:d.sms,whatsapp:d.whatsapp,phoneLast4:d.phone?.slice(-4)||null,preferences:d.preferences});
if(b.action==='preferences'){await db('rb_push_devices?id=eq.'+d.id,'PATCH',{preferences:preferences(b.preferences),updated_at:new Date().toISOString()});return json({saved:true})}
if(b.action==='unsubscribe'){if(!['push','sms','whatsapp','all'].includes(b.channel))throw new Failure(400,'Unknown channel');if(b.channel==='all')await db('rb_push_devices?id=eq.'+d.id,'DELETE');else await db('rb_push_devices?id=eq.'+d.id,'PATCH',b.channel==='push'?{subscription:null}:{[b.channel]:false});return json({removed:true})}
if(b.action==='bind'){if(!uuid(b.thread)||!/^[a-f0-9]{64}$/.test(b.threadToken||''))throw new Failure(400,'Invalid conversation');await db('rpc/rb_push_bind_thread','POST',{p_device:d.id,p_thread:b.thread,p_token:b.threadToken});return json({saved:true})}
if(b.action==='test'){await limit('test:'+d.id,5);if(!d.subscription)throw new Failure(400,'Enable browser push first');await db('rb_push_jobs','POST',{device_id:d.id,event_key:'test:'+crypto.randomUUID(),kind:'test'});return json({queued:true})}
if(b.action==='phone-start'||b.action==='phone-finish'){
 const enabled=channels();if(!phoneReady()||!(b.sms&&enabled.sms||b.whatsapp&&enabled.whatsapp)||b.consent!==true)throw new Failure(503,'Phone notifications are not configured, or consent is missing.');
 if(!/^\+[1-9][0-9]{7,14}$/.test(b.phone||''))throw new Failure(400,'Use an international phone number, for example +49…');
 if(b.action==='phone-start'){await limit('otp-device:'+d.id,3);await limit('otp-number:'+await hash(b.phone),3);const cr=await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify',{method:'POST',body:new URLSearchParams({secret:env('TURNSTILE_SECRET_KEY'),response:b.captcha||''})});const captcha=await cr.json();if(!captcha.success||captcha.hostname!==new URL(SITE).hostname)throw new Failure(403,'Complete the verification challenge');await twilio('Verifications',{To:b.phone,Channel:'sms'},true);await db('rb_push_devices?id=eq.'+d.id,'PATCH',{pending_phone:b.phone,pending_expires:new Date(Date.now()+10*60000).toISOString()});return json({codeSent:true})}
 await limit('otp-check:'+d.id,6);if(d.pending_phone!==b.phone||Date.parse(d.pending_expires)<Date.now()||!/^\d{4,10}$/.test(b.code||''))throw new Failure(400,'Verification expired or invalid');const verified=await twilio('VerificationCheck',{To:b.phone,Code:b.code},true);if(verified.status!=='approved')throw new Failure(400,'Incorrect verification code');await db('rb_push_devices?id=eq.'+d.id,'PATCH',{phone:b.phone,sms:Boolean(b.sms&&enabled.sms),whatsapp:Boolean(b.whatsapp&&enabled.whatsapp),pending_phone:null,pending_expires:null,updated_at:new Date().toISOString()});return json({verified:true})}
throw new Failure(400,'Unknown action');
}catch(e:any){return json({error:e instanceof Failure?e.message:'Request could not be completed.'},e instanceof Failure?e.status:400)}});

